(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes
lib.webFontTxtFilters = {}; 

// library properties:
lib.properties = {
	width: 300,
	height: 250,
	fps: 24,
	color: "#FFFFFF",
	webfonts: {},
	manifest: [
		{src:"images/bg_300_2.jpg", id:"bg_300_2"},
		{src:"images/Bitmap2.png", id:"Bitmap2"},
		{src:"images/Bitmap3.png", id:"Bitmap3"},
		{src:"images/hl2.png", id:"hl2"},
		{src:"images/Mouse_Pointer_Wolfram_Es_clip_art_hight.png", id:"Mouse_Pointer_Wolfram_Es_clip_art_hight"},
		{src:"images/mr_UW.jpg", id:"mr_UW"}
	]
};



lib.webfontAvailable = function(family) { 
	lib.properties.webfonts[family] = true;
	var txtFilters = lib.webFontTxtFilters && lib.webFontTxtFilters[family] || [];
	for(var f = 0; f < txtFilters.length; ++f) {
		txtFilters[f].updateCache();
	}
};
// symbols:



(lib.bg_300_2 = function() {
	this.initialize(img.bg_300_2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,194);


(lib.Bitmap2 = function() {
	this.initialize(img.Bitmap2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,98,15);


(lib.Bitmap3 = function() {
	this.initialize(img.Bitmap3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,180,97);


(lib.hl2 = function() {
	this.initialize(img.hl2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,158,91);


(lib.Mouse_Pointer_Wolfram_Es_clip_art_hight = function() {
	this.initialize(img.Mouse_Pointer_Wolfram_Es_clip_art_hight);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,36,35);


(lib.mr_UW = function() {
	this.initialize(img.mr_UW);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,50,67);


(lib.Tween4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Mouse_Pointer_Wolfram_Es_clip_art_hight();
	this.instance.setTransform(-18,-17.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-18,-17.5,36,35);


(lib.Tween3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Mouse_Pointer_Wolfram_Es_clip_art_hight();
	this.instance.setTransform(-18,-17.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-18,-17.5,36,35);


(lib.Tween2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Mouse_Pointer_Wolfram_Es_clip_art_hight();
	this.instance.setTransform(-18,-17.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-18,-17.5,36,35);


(lib.Tween1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Mouse_Pointer_Wolfram_Es_clip_art_hight();
	this.instance.setTransform(-18,-17.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-18,-17.5,36,35);


(lib.c2a = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// svg1878
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#233C4C").s().p("AguA3IA1g3Ig1g2IATgUIBKBKIhIBLg");
	this.shape.setTransform(-19.7,65);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer 2 copy
	this.instance = new lib.Bitmap2();
	this.instance.setTransform(-7,57);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Layer 4
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#EDC100").s().p("AFcC2IgKAAIgKgBIgPABIgXgBIgZAAIgCgBIgKABIgOAAIgdgCIiCgCIgeABQAJAAgBABIiUAAIidAAImjABIABiOIAChhIABg8IgBABIABgWIABgYIAAgKIAMAAIgCAAIABAAIABgBQAAAAABAAQAAAAgBAAQAAAAAAAAQAAAAgBAAIACAAIADAAIAIAAIACAAIACAAIAJgBIASAAIAGAAIAHAAIgFAAIgCAAIgGAAIgMgBIAAAAIgDgBIABAAIAJgBIAIABQAKAAgEABIATgBIANAAIAQAAIANACIgOAAIgNAAIAKAAIAIAAIALAAIAGAAIAzAAIgFAAIAVAAQgCAAADgBIALgBIADAAIBXgDIAMAAIABAAIAJAAIAKABIAOgBIAYABIAYAAIACABIALAAIAOAAIAcABIBCAAIBBACIArAAIgNgBQgJAAAAgBICVAAICcABIB2gBICHAAICngBIgCCOQABAhgCBAIgBA7IgBAWIgBAYIAAAKIgYAAIAJAAIADAAQABAAABAAQAAAAABAAQAAAAAAABQgBAAAAAAIgCAAIACAAIgaADIgFAAIgIAAIgIAAIgGAAIgBAAIgSAAIgNAAIgQAAQgMAAgBgCIAaAAIgKAAIgIAAIgKAAIgGAAIhAAAIgFAAQABAAABAAQAAABABAAQAAAAgBAAQAAAAgBAAIgLABIgDAAIgsACIgsABIgLAAgAJSCxIAGAAIAGABIALAAIAHgBIgKAAIgKAAIACAAIgMAAgAJyCxIABAAIANgBgAp9iuIgJAAIgDAAIAMAAIAAAAg");
	this.shape_1.setTransform(35.2,64.5);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-31.6,46.2,133.6,36.6);


(lib.HL2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.instance = new lib.hl2();
	this.instance.setTransform(-4,-2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Long highlight device
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#004EB6").s().p("A0lEYQgMgDgEgDQgGgDgagCQgGgBgJgFQAAADgGACQgHACAAACIgEAAQgSgCgIgEQgIgFgCgJIAAgDQgBgCgHABQAAAAgBAAQgBAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAQAGgBAGgEQAGgFAFgBQABAAABAAQABgBAAAAQAAAAAAAAQAAgBAAAAIgFgBQghgJAegMQAGgCAAgCQABgDgGgBQgNgDAHgFIAEgDQABgCgFgCQAAAAgBAAQAAgBAAAAQAAAAAAAAQABAAAAgBIAFgBQAXgDgSgLQgOgIANgEQAFgCAAgDIgDgLQgCgHABgEQAAAAAAgBQAAAAAAAAQgBgBAAAAQgBAAgBgBQgKgDACgDQABgDAKgDQgLgEgCgGQgBgFAIgFIABgBQgEgFAGgIQAGgJAAgEQAAgDgJgIQgHgHACgFIABgEQABgCAFgBQAGgBgEgDQgIgIASgBQgKgDgBgDQgCgDAGgEQAHgEgHgDQgQgGAOgHIACgBQABAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAgBQgFgHADgLIAGgSQAAgFgIgJQgIgJADgFQABgDgHAAIgEgBQAAAAAAAAQAAAAAAgBQgBAAABAAQAAAAAAAAQAFgBADgEQADgFAEgBQAXgFgSgIIgGgCQgBgBAIgCQAKgCABgIQAAgGgIgFQgJgFAIgEQAFgDABgCQAAgCgHgCIgEgCQAHgDgGgGQgFgHAIgEQAFgCgCgIQgCgJAHgDQABgBAAAAQAAAAAAgBQAAAAAAAAQAAgBgBAAIgFgBQgEgEAAgCQAAgCAKgBIAGAAQABAAAAAAQABAAAAAAQABAAAAgBQAAAAAAgBQAAgFgFgBQgGAAgBgCIAAgEQABgCAEAAIAIAAQAPAAAHgBQAKgCACgHQABgCALAAQBygCA5ABIAfgCQASgBANACQACAAAJgCQAIgDAHABIAJAAQAGAAADADQACACAKAAQAKAAACgBQAEgDAHAAIALAAIA2ABQAEAAADgCQAEgDAFAAQAFABADADQAEAEAHgCQAPgEAXABIAmAAIASAAQAKAAAHgDQAHgDAIAEIAJADQAGAAAEgEQACgBAEAAQAEABACACQAIAFAIgFQACgBAKAAIA2AAIAGABQABAAAAAAQABAAABgBQAAAAAAgBQABAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAQABAAAAAAIAFAAQALAEATgDQAVgCAJABQASACAxgBIAQABQAIgBAGgDQADgBAFABQAJAEANgCQASgDAFABIA1ACIAKAAQAFAAACgEQABgCAQABQAQABAEACQAFADAKAAQAKAAAFgDQACgBAKAAQAlAAALABIAOABQAJAAAGgFQAEgDAaADQANABAKAAQAXgBAvACIBFAAIAKABQAFgBABgDQABAAAAgBQAAAAAAAAQABAAAAAAQABAAAAAAQADAAADABQAHAEAEAAQAFAAAGgEQACgBADABQAFABAPgBQANAAAGAFQADACACgBQALgFASAAIAeABIAXABQAOAAAEgBQAOgDAMAEIAFABQABAAAAAAQABAAAAAAQABgBAAAAQAAAAAAAAQAFgEACgBQAEAAADAFIAGAAQAIgGAPABIAYABQAyACBhACIAyAAIALABQAHgBACgDQAAgCAHAAQAGAAADADQACADAGAAQAFABAFgCQAKgEAEABQAEAAAGAFIANgFQAIgCAHAGQAEAFALgEQAXgIAPAJQAEACAEgCQANgEASAAQARAAAMAEQADABAIgCQARgGAEAJQABACADAAIAHAAIB9AAQAGgDAKAAIASABIAJAAQAFAAAAgEQAAgBAGAAIAIABQASAFASgHQAEgCADACQAFACAGAAQAGgBADgDQABgBAIAAIAJAAQABADAIAAQAIAIAFgEQADgBACgFQAEgFAJAAIAPACQAPADAGgCQAOgFAXgBIAngBIChgHQAIAAAAgBQACgHAOAAIAVAAIAXgEQAWgEAwABQABAAAAABQABAAABAAQAAABAAAAQABAAAAABIAAADQABABAAAAQABAAAAAAQABAAABAAQAAAAABgBQABAAABAAQABAAAAAAQABAAAAABQABAAAAAAQABAEgKAAQgBADgJAFQgJAEgBACQgGALAKAGQANAGgHALQgCACAAADIgBAEQAAACACAJQACAGgGAEQgEADAAACQAAAFANAAIABACIgBACQgCAEgFAOIgCAJQAAADAJAGIACADQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAQgEACgBAFQgCAFgGACIAAAAQgEADAGADQAHADgDACQgJAGANADIADACQABAAAAAAQAAAAAAABQAAAAAAAAQAAAAgBAAQgIACABAGQABAGgGACIgBACQALABgBAEQAAAGABABQAFAEgJACQgFAAABAFQAHAQgEAIQgBACAHAJQAEAGgBAJIgFANQgBAGAFANIACAFQAAACgIABQgDABACAFIAIATQAEAMgEAHIAAAPQABAIgKAFQgBABAAAAQAAAAAAABQgBABAAAAQAAABAAABQABADAFABQAFABABABIABADQAFAJgOAEQgKADAKABQAFAAAAADQABADgDAFQgCAFAIACQAAAAABABQAAAAAAAAQAAAAAAABQAAAAAAAAQAAABgBAAQAAABAAAAQgBAAAAAAQgBAAgBAAQgKABgCADIAAAGQACAGgGAEQgEACABADQABAEAGADQAHADABAFQACAFgEAEQgFAFAAADIgDANQgDAHAEAGQABABgJACQgIACgDgBQgIgCgJABQgJABgCACQgDAFgOAAQgkAAgTABIgeAAQgUgCgKABIgSABQgKAAgGADQgHAEgGgEQgCgCgSAAQgRAAgEACQgLAEgGAAQgFABgRgDQgUgEgHAHQgCAEgJAAIgcABQgOABgGgEQgEgDgKABIgRADIgOAAQgEgBAAgEQAAgEgNAAIi/AAQgBAAgBABQgBAAAAAAQAAABgBAAQAAABAAAAQABAEgFABIgLAAQihgChRgDIgMAAQgHAAgDAEQgBACgJAAQgIAAgEgCQgNgHgVAFIgGABQgPgEgFAAQgFAAgSAEQgQAEgJgGQgDgCgFgBQgFAAgDABQgIADgOAAIgWAAQgFAAgCgCQgCgDgDAAQgFgBgHACIgKACIhgAAQgQAAgGgEQgDgCgDACQgFADgDAAQgqABgVgCQgmgDgmADQgYACgNAAQgPAAgDgDQgBgCgEAAQgBAAgBAAQgBAAAAABQgBAAAAAAQAAAAAAAAQAAAFgHAAIgKgBQgNgBguAAQgKAAgCABQgGAFgDgGIgGAAQgMAEgTgBIggAAQgHABgBgDQgBgDgEAAQgFgBgCABQgJAEgPgBIgYAAIgKAAQgGABgCACQAAABgBAAQAAAAgBABQAAAAgBAAQAAAAgBgBQgNgEgXADQgaACgLgBQgFgBgCADQgCAEgHgEIgHgDQgDgBgCAEQgCACgDAAIgHAAQg5gEglAEQgkADgcgBQgvgDgbACQgjADgbAAQgZAAgHgCQgHgBgEACQgJAFgQgBIgbAAIgPgBQgJgBgFADQgEADgEgDQgGgFgHAFQgCACgEgCQgKgCgUACQgUABgJgBIgbgDQgQgCgNABQhbAHgmgBQgPAGgaABIgrABIhYACIgCAAQgFAAgLgDg");
	this.shape.setTransform(107.4,43.2,0.259,0.52);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-4,-2,158,91);


(lib.HL = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 4 copy
	this.instance = new lib.Bitmap3();
	this.instance.setTransform(-5,-2.2,0.9,0.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Long highlight device
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#004EB6").s().p("A0lEYQgMgDgEgDQgGgDgagCQgGgBgJgFQAAADgGACQgHACAAACIgEAAQgSgCgIgEQgIgFgCgJIAAgDQgBgCgHABQAAAAgBAAQgBAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAQAGgBAGgEQAGgFAFgBQABAAABAAQABgBAAAAQAAAAAAAAQAAgBAAAAIgFgBQghgJAegMQAGgCAAgCQABgDgGgBQgNgDAHgFIAEgDQABgCgFgCQAAAAgBAAQAAgBAAAAQAAAAAAAAQABAAAAgBIAFgBQAXgDgSgLQgOgIANgEQAFgCAAgDIgDgLQgCgHABgEQAAAAAAgBQAAAAAAAAQgBgBAAAAQgBAAgBgBQgKgDACgDQABgDAKgDQgLgEgCgGQgBgFAIgFIABgBQgEgFAGgIQAGgJAAgEQAAgDgJgIQgHgHACgFIABgEQABgCAFgBQAGgBgEgDQgIgIASgBQgKgDgBgDQgCgDAGgEQAHgEgHgDQgQgGAOgHIACgBQABAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAgBQgFgHADgLIAGgSQAAgFgIgJQgIgJADgFQABgDgHAAIgEgBQAAAAAAAAQAAAAAAgBQgBAAABAAQAAAAAAAAQAFgBADgEQADgFAEgBQAXgFgSgIIgGgCQgBgBAIgCQAKgCABgIQAAgGgIgFQgJgFAIgEQAFgDABgCQAAgCgHgCIgEgCQAHgDgGgGQgFgHAIgEQAFgCgCgIQgCgJAHgDQABgBAAAAQAAAAAAgBQAAAAAAAAQAAgBgBAAIgFgBQgEgEAAgCQAAgCAKgBIAGAAQABAAAAAAQABAAAAAAQABAAAAgBQAAAAAAgBQAAgFgFgBQgGAAgBgCIAAgEQABgCAEAAIAIAAQAPAAAHgBQAKgCACgHQABgCALAAQBygCA5ABIAfgCQASgBANACQACAAAJgCQAIgDAHABIAJAAQAGAAADADQACACAKAAQAKAAACgBQAEgDAHAAIALAAIA2ABQAEAAADgCQAEgDAFAAQAFABADADQAEAEAHgCQAPgEAXABIAmAAIASAAQAKAAAHgDQAHgDAIAEIAJADQAGAAAEgEQACgBAEAAQAEABACACQAIAFAIgFQACgBAKAAIA2AAIAGABQABAAAAAAQABAAABgBQAAAAAAgBQABAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAQABAAAAAAIAFAAQALAEATgDQAVgCAJABQASACAxgBIAQABQAIgBAGgDQADgBAFABQAJAEANgCQASgDAFABIA1ACIAKAAQAFAAACgEQABgCAQABQAQABAEACQAFADAKAAQAKAAAFgDQACgBAKAAQAlAAALABIAOABQAJAAAGgFQAEgDAaADQANABAKAAQAXgBAvACIBFAAIAKABQAFgBABgDQABAAAAgBQAAAAAAAAQABAAAAAAQABAAAAAAQADAAADABQAHAEAEAAQAFAAAGgEQACgBADABQAFABAPgBQANAAAGAFQADACACgBQALgFASAAIAeABIAXABQAOAAAEgBQAOgDAMAEIAFABQABAAAAAAQABAAAAAAQABgBAAAAQAAAAAAAAQAFgEACgBQAEAAADAFIAGAAQAIgGAPABIAYABQAyACBhACIAyAAIALABQAHgBACgDQAAgCAHAAQAGAAADADQACADAGAAQAFABAFgCQAKgEAEABQAEAAAGAFIANgFQAIgCAHAGQAEAFALgEQAXgIAPAJQAEACAEgCQANgEASAAQARAAAMAEQADABAIgCQARgGAEAJQABACADAAIAHAAIB9AAQAGgDAKAAIASABIAJAAQAFAAAAgEQAAgBAGAAIAIABQASAFASgHQAEgCADACQAFACAGAAQAGgBADgDQABgBAIAAIAJAAQABADAIAAQAIAIAFgEQADgBACgFQAEgFAJAAIAPACQAPADAGgCQAOgFAXgBIAngBIChgHQAIAAAAgBQACgHAOAAIAVAAIAXgEQAWgEAwABQABAAAAABQABAAABAAQAAABAAAAQABAAAAABIAAADQABABAAAAQABAAAAAAQABAAABAAQAAAAABgBQABAAABAAQABAAAAAAQABAAAAABQABAAAAAAQABAEgKAAQgBADgJAFQgJAEgBACQgGALAKAGQANAGgHALQgCACAAADIgBAEQAAACACAJQACAGgGAEQgEADAAACQAAAFANAAIABACIgBACQgCAEgFAOIgCAJQAAADAJAGIACADQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAQgEACgBAFQgCAFgGACIAAAAQgEADAGADQAHADgDACQgJAGANADIADACQABAAAAAAQAAAAAAABQAAAAAAAAQAAAAgBAAQgIACABAGQABAGgGACIgBACQALABgBAEQAAAGABABQAFAEgJACQgFAAABAFQAHAQgEAIQgBACAHAJQAEAGgBAJIgFANQgBAGAFANIACAFQAAACgIABQgDABACAFIAIATQAEAMgEAHIAAAPQABAIgKAFQgBABAAAAQAAAAAAABQgBABAAAAQAAABAAABQABADAFABQAFABABABIABADQAFAJgOAEQgKADAKABQAFAAAAADQABADgDAFQgCAFAIACQAAAAABABQAAAAAAAAQAAAAAAABQAAAAAAAAQAAABgBAAQAAABAAAAQgBAAAAAAQgBAAgBAAQgKABgCADIAAAGQACAGgGAEQgEACABADQABAEAGADQAHADABAFQACAFgEAEQgFAFAAADIgDANQgDAHAEAGQABABgJACQgIACgDgBQgIgCgJABQgJABgCACQgDAFgOAAQgkAAgTABIgeAAQgUgCgKABIgSABQgKAAgGADQgHAEgGgEQgCgCgSAAQgRAAgEACQgLAEgGAAQgFABgRgDQgUgEgHAHQgCAEgJAAIgcABQgOABgGgEQgEgDgKABIgRADIgOAAQgEgBAAgEQAAgEgNAAIi/AAQgBAAgBABQgBAAAAAAQAAABgBAAQAAABAAAAQABAEgFABIgLAAQihgChRgDIgMAAQgHAAgDAEQgBACgJAAQgIAAgEgCQgNgHgVAFIgGABQgPgEgFAAQgFAAgSAEQgQAEgJgGQgDgCgFgBQgFAAgDABQgIADgOAAIgWAAQgFAAgCgCQgCgDgDAAQgFgBgHACIgKACIhgAAQgQAAgGgEQgDgCgDACQgFADgDAAQgqABgVgCQgmgDgmADQgYACgNAAQgPAAgDgDQgBgCgEAAQgBAAgBAAQgBAAAAABQgBAAAAAAQAAAAAAAAQAAAFgHAAIgKgBQgNgBguAAQgKAAgCABQgGAFgDgGIgGAAQgMAEgTgBIggAAQgHABgBgDQgBgDgEAAQgFgBgCABQgJAEgPgBIgYAAIgKAAQgGABgCACQAAABgBAAQAAAAgBABQAAAAgBAAQAAAAgBgBQgNgEgXADQgaACgLgBQgFgBgCADQgCAEgHgEIgHgDQgDgBgCAEQgCACgDAAIgHAAQg5gEglAEQgkADgcgBQgvgDgbACQgjADgbAAQgZAAgHgCQgHgBgEACQgJAFgQgBIgbAAIgPgBQgJgBgFADQgEADgEgDQgGgFgHAFQgCACgEgCQgKgCgUACQgUABgJgBIgbgDQgQgCgNABQhbAHgmgBQgPAGgaABIgrABIhYACIgCAAQgFAAgLgDg");
	this.shape.setTransform(85.9,13.7,0.3,0.545);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-5,-2.2,162,114.6);


(lib.Symbol1copy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0072CE").s().p("AJCF7IAAAAQAAgBgQAAQgRAAAAgBQgXAAgBABQgPAAgZgBQgWgCgSABIgDgCQgKAAgIABIgXAAIgvgDIjYgDIhIAAIAVABQAPAAgBABIj3AAQioAAhdgBIq5ADIADkiIAAgDQAAhGACiGIACh8IgBACQACgVAAgZQAAgZACgYIAAgVIAoAAQgDgBgNAAIgEAAIgFAAIACgBQAAAAAAAAQAAAAAAAAQABAAAAgBQABAAABAAQAAAAAAAAQAAAAAAAAQgBAAgBAAQgBAAgBAAIA3gEQgBAAgBgBQgBAAgBAAQAAAAgBAAQAAgBABAAQgBAAgBAAQAAAAAAAAQAAAAABAAQAAAAABAAIAPgBIANABQARAAgGACIAggBIAUAAIAcAAQATABABABIgWAAIgVABIAQAAIAOABQAJABAIgBIAKgCIBqACIhFgDIAjgBQgBAAgBAAQgBAAAAAAQAAABAAAAQAAAAAAAAIAFABIAqAAQgCAAgCAAQgBAAAAAAQgBAAABAAQAAgBABAAIASgBIAGAAICRgIIAUAAIAAAAQgBABARAAQARAAAAABQAWAAACgBQAOAAAZACQAYABARgBIADACIASAAQAGgBARAAIAvADIBtABIBsACIBIAAIgWgBQgPAAABgBID4AAIEDABIDEgCIDhAAIEVgBIgDElQABBFgECIIgCB7IABgCIgCAuQAAAZgBAYIAAAVIgoAAQACABANAAIAFAAQACAAABAAQABAAAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAQAAAAAAAAQgBAAAAABQgBAAAAAAIgBAAIgHAAIgiABIACABIACAAIAYgBIANgBIAAAAIACABIgrAEIgGgBQAEABgFAAIgNAAIgOAAIgLAAIgBAAIgeAAIgWAAIgbAAQgTgBgBgBQAfAAAMgBIgRAAIgNgBQgJgBgHABIgLACIhpgCIgKACQACAAABAAQABAAAAAAQABAAgBAAQAAABgBAAIgSABIgHAAIhIAEIhJAEIgTAAgAPvFxIATAAIALAAIgRAAIgRgBIAFAAIgVAAIAHABIAEgBQgCABALAAgAwhltIAGAAIAOgBIgCAAIgCgBIAnAAIgFABIAVgBIgIgBIgDABQABgBgLAAIgTgBQgwADAHABIgLAAIAHAAIAMAAg");
	this.shape.setTransform(110.9,37.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,221.8,75.9);


(lib.logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AACADIgCgCIgCgBIgCAAIABgBIACAAIABgBIABAAQABAAABAAQAAAAABABQAAAAAAAAQABABAAAAIgBABQAAABAAAAQAAAAgBAAQAAABAAAAQAAAAgBAAIAAAAg");
	this.shape.setTransform(-45.4,43.9,0.354,0.354);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgDAEIgEgCIADgCQAAgBAAAAQABgBAAAAQABAAAAAAQABgBABAAIADABIADgBQAAAAAAAAQABAAAAAAQAAAAAAAAQAAABABAAQACACgDACQgCACgFAAIgDAAg");
	this.shape_1.setTransform(-47.7,44.1,0.354,0.354);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgDAAIACAAIAAAAQABgBAEAAIgDABIgDACIgBAAQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAgBg");
	this.shape_2.setTransform(-46.3,44.1,0.354,0.354);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAAABIAAgBIAAAAIAAAAIABAAIAAAAIAAAAIAAABg");
	this.shape_3.setTransform(-47.8,43.5,0.354,0.354);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAAABIgBgBIABAAIABgBIABABIgBAAIgBAAIABAAQAAABAAAAQAAAAgBAAQAAABAAAAQAAAAAAAAg");
	this.shape_4.setTransform(-47.6,43.4,0.354,0.354);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgDACQAAgBADgBIAEgCIAAACIgDAAIgBABIgBACg");
	this.shape_5.setTransform(-47.6,43.2,0.354,0.354);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAAACIgBgCQgBAAABAAQAAAAAAAAQAAAAABAAQAAgBAAAAQAAgBAAAAQABAAAAAAQABAAAAAAQAAAAABABIgCABIgBACIAAABIAAgBg");
	this.shape_6.setTransform(-47.7,43,0.354,0.354);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgCAAIAAAAIAAgBIACABIABAAIACAAIAAABQAAABAAAAQAAAAgBAAQAAAAgBAAQgBAAAAAAQAAAAAAAAQAAAAAAgBQgBAAAAgBQAAAAgBAAg");
	this.shape_7.setTransform(-48,43.1,0.354,0.354);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgDACIABgBIADgCQAAgBABAAQABAAAAAAQABAAAAAAQAAAAAAABIgEACIgBABIgBABIgBgBg");
	this.shape_8.setTransform(-48.1,42.7,0.354,0.354);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgBABQAAgBAAAAQgBAAABAAQAAAAAAAAQAAAAABAAIAAAAIABAAIABAAQAAAAAAAAQABAAgBAAQAAAAAAAAQgBAAAAAAIgBAAIAAABIgBAAg");
	this.shape_9.setTransform(-50.4,43,0.354,0.354);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgBABQgBAAAAAAQAAAAAAAAQAAAAAAAAQAAgBAAAAIACAAIAAAAQAAAAABAAQAAAAABgBQAAAAABABQAAAAAAAAIAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAQgBABAAAAg");
	this.shape_10.setTransform(-49.9,42.8,0.354,0.354);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgBAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAAAIABAAIABAAIAAAAIgCABQAAAAAAAAQAAgBgBAAQAAAAAAAAQAAAAAAAAg");
	this.shape_11.setTransform(-45.1,41.6,0.354,0.354);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgCAEIgDgCQAAgBAAAAQAAgBAAAAQAAAAAAAAQAAAAABAAQACgDAGAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAQAAAAAAABQAAAAAAAAQgBAAAAAAQgBAAAAAAIgDADIgBABIgCAAg");
	this.shape_12.setTransform(-44.9,41.4,0.354,0.354);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAAABIAAgBIAAAAIAAAAIAAAAIABAAQAAAAAAAAQAAABAAAAQAAAAAAAAQgBAAAAAAg");
	this.shape_13.setTransform(-44.7,41.1,0.354,0.354);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgCADQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAAAAAgBIACAAIABgBQAAgBAAAAQABAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAABAAAAQAAABgBAAQAAAAgBAAQAAABgBABQAAAAAAABQAAAAAAAAQAAAAAAAAIgCAAg");
	this.shape_14.setTransform(-46.9,41.1,0.354,0.354);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAAAAIAAgBQABAAAAAAQABAAAAABQAAAAgBAAQAAAAgBAAIAAACIAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAQABgBAAAAg");
	this.shape_15.setTransform(-46.6,40.8,0.354,0.354);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgDACIABgCIABAAIABAAQAAgBAAAAQABAAAAAAQABAAAAAAQABAAAAABIAAAAIgCABIgBAAIgCABIgBAAg");
	this.shape_16.setTransform(-44.4,40.5,0.354,0.354);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgBAAQAAgBAAAAQABAAAAgBQAAAAAAAAQAAAAAAAAIABAAQABAAAAABQAAAAAAAAQAAABgBAAQAAAAgBAAIgBADg");
	this.shape_17.setTransform(-44.5,40.1,0.354,0.354);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgFAGIABgBIADgDIADgFIADgCIABAAQAAABAAAAQAAAAAAABQAAAAAAAAQAAABgBAAIgCACIgBAAIgBACIgBABIAAABIgCABIgCABIgBAAg");
	this.shape_18.setTransform(-45.9,40.3,0.354,0.354);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgBABIABgBIAAAAIAAAAIABAAQABAAAAAAQAAAAAAAAQAAAAgBAAQAAABAAAAIgBABIgBgBg");
	this.shape_19.setTransform(-45,40.3,0.354,0.354);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAAAAIAAAAQAAAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQgBAAAAAAIAAAAg");
	this.shape_20.setTransform(-45.2,40.8,0.354,0.354);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAAAAIAAAAIABAAQAAAAAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAIAAABIAAgBg");
	this.shape_21.setTransform(-46.8,40.4,0.354,0.354);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgCAEIgBgCIABgCQABAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAAAQABgBAAgBQABAAAAgBQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABQAAAAgBABQAAAAAAAAIgBACIgCABIAAAAIgBABIgBAAg");
	this.shape_22.setTransform(-48.4,42.6,0.354,0.354);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgDAFQAAAAAAgBQgBAAAAAAQAAgBAAgBQAAAAABgBIAAgBIAAAAQABAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAIgBgBIAAgCIAAgBQAAAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAAAIACABIABAAIACgBIACABQAAABAAAAQAAAAgBABQAAAAAAAAQAAAAAAAAIgBgBIgBAAQgBAAAAABQAAAAAAAAQAAABAAAAQAAAAAAAAIAAADQgBABAAAAQAAABAAAAQAAAAAAAAQAAAAAAAAIgDAAg");
	this.shape_23.setTransform(-46.8,44.2,0.354,0.354);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgEAIIgBgCQgBgFADgEQADgGABAAQACgBACADQADAFgDADIgEAGIgBADIAAAAQgBAAAAAAQgBAAAAAAQAAAAgBgBQAAAAgBgBg");
	this.shape_24.setTransform(-54.7,32.3,0.354,0.354);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AAAAJIgEgCIgBgEIgBgDIgBgBIAAgCQABAAAAgBQAAAAAAgBQABAAAAgBQAAAAgBAAIABgCIAGABIAEAFIACAEQABABAAAAQAAABgBAAQAAAAAAABQAAAAgBAAIgDADIgBACg");
	this.shape_25.setTransform(-53.3,32.1,0.354,0.354);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgFAHQgDgBgBgDQABgDAFgCIAHgDQAFgCAAAFIABACQAAAAAAAAQAAAAAAAAQAAAAgBABQAAAAgBABIgIAFg");
	this.shape_26.setTransform(-56.1,31.5,0.354,0.354);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgGAEIgCgBQAAAAgBgBQAAAAgBgBQAAAAAAgBQAAAAAAAAIgBAAQgBgBAAgBQAAAAAAgBQABAAAAAAQAAgBABAAIADAAQADgBAEABIAEAAIAGACQABAAAAABQABAAAAAAQABABAAAAQAAAAAAAAIgDABQgBAEgDgBIgEABQgGAAgCgBg");
	this.shape_27.setTransform(-52.3,30.8,0.354,0.354);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgSAiIgGgEQgEAAgCgCQgCgBAAgFQABAAAAgBQAAAAgBAAQAAgBAAgBQAAAAgBgBQgCgEgBgDIAAgEQAAgEACgCQAEgEgDgBQgCgBADgEQABgBADgGQAEgGAGgCQAEgBAGgFQAFgFADAAQAFgBAFACIAGACQADABABACIAEAEIAFAFIAGAIIABAJQABAIgDAFQgCAGgIAHQgKAJgMADIgJACIgCAAQgFAAgEgDgAgBgOIgGADIgEADQgEADgDAKQgCAEADADQACADADAAIAJgBQAFgCAFgHIAHgHQADgEgBgCQgCgEgEgBIgHgBIgCgBIgCABg");
	this.shape_28.setTransform(-54.2,30.3,0.354,0.354);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgDAFIgDgBIgDgCQgCgCABgCQABgBAEgCQAEgBABACQAEACAGAAIABACIgBADIgHADIgDAAIgDgBg");
	this.shape_29.setTransform(-56.1,30,0.354,0.354);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgFAHQAAgBgEgCQgCgCAAgCQAAAAAAAAQABAAAAAAQABgBAAAAQABAAAAgBQAEgBABgBIAHgCQAHgBACABIAAABIgEAEQAAAAAAABQgBAAAAAAQAAAAAAAAQAAAAAAABQABAAgBABQAAAAAAABQAAAAgBABQgBAAAAAAIgGADIgDABIgCgBg");
	this.shape_30.setTransform(-52.6,29.2,0.354,0.354);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgGAGIAAgEIAAgKQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAEABIACAFIADAGIACAEQAAABAAAAQAAABAAAAQAAAAAAABQAAAAAAAAIgDABIgBABQgGAAgDgFg");
	this.shape_31.setTransform(-55.2,28.9,0.354,0.354);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgEALIgBgDIAAgEQgBgEADgDQACgFABgBQAAgBABAAQABAAAAgBQABAAAAAAQAAAAABAAQACACAAAEIAAAFQABABgEAFIgBADIgCACIgCABIgCgBg");
	this.shape_32.setTransform(-53.9,28.3,0.354,0.354);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgBABIABgBIAAAAIABAAIABAAIgBAAIgBABg");
	this.shape_33.setTransform(-44.7,43.5,0.354,0.354);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgDACQgBgCADgCQABAAAAAAQAAAAAAgBQAAAAAAAAQAAAAABAAQABAAAAAAQABAAAAAAQAAAAABABQAAAAAAAAQACACgFADIgCABQAAAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAg");
	this.shape_34.setTransform(-44.5,43.2,0.354,0.354);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQABAAAAAAQAAAAgBAAQAAABAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAgBQAAAAAAAAg");
	this.shape_35.setTransform(-43.9,43,0.354,0.354);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgBAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAABAAIAAgBQABAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAAAIgCABIAAABQAAABAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAg");
	this.shape_36.setTransform(-49,42.6,0.354,0.354);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AAAABQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAg");
	this.shape_37.setTransform(-47.1,42.1,0.354,0.354);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgBAAQABAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAIABAAIAAAAIAAAAIgBAAIAAABQAAAAAAAAQAAAAAAAAQAAAAgBgBQAAAAAAAAg");
	this.shape_38.setTransform(-43.6,41.8,0.354,0.354);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgGACIAAgCIACAAIAEAAQAAAAAAAAQAAAAAAAAQABAAAAAAQABAAAAgBIADgBQAAgBABAAQAAAAAAAAQABABAAAAQAAAAAAABIgBABIgBAAIgDADIgDABQgEAAgBgCg");
	this.shape_39.setTransform(-46.8,41.8,0.354,0.354);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AAAAAIAAAAIABAAQAAAAAAABQAAAAAAAAQgBAAAAAAQAAABAAAAQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAAAAAAAg");
	this.shape_40.setTransform(-46.4,41.6,0.354,0.354);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AAAACIAAgCIAAgBQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAIABABIgBACg");
	this.shape_41.setTransform(-44.3,41.5,0.354,0.354);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AgFAGQgEgDAFgDIAFgEQAEgCACABQAAAAAAABQABAAAAABQAAAAgBABQAAAAAAABIgDACQgCADgCACIgDABIgCgBg");
	this.shape_42.setTransform(-48.2,41.6,0.354,0.354);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AgEABIACgBIACAAIAAgCIABAAIABABIADAAIgBAAIgCABIgCAAIgBADIgBAAIgBAAQAAAAgBAAQAAAAAAAAQAAgBAAAAQAAAAAAgBg");
	this.shape_43.setTransform(-46,41.3,0.354,0.354);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AAAABQAAgBAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAIABAAIAAABg");
	this.shape_44.setTransform(-45.9,41.1,0.354,0.354);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("AgFAEQAAAAAAgBQAAAAAAAAQAAgBAAAAQABgBAAAAIADgBIABgBIADgCQABgBAAAAQABAAAAAAQAAABABAAQAAAAAAABIAAACQAAAAAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAIgDABIgCAAQAAAAgBAAQgBAAAAAAQAAABAAAAQAAAAABABQAAAAAAAAQAAAAAAAAQAAAAgBABQAAAAAAAAIgBABIgCgBg");
	this.shape_45.setTransform(-43.9,41.2,0.354,0.354);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("AgIAKQAAgBAAAAQAAAAAAgBQAAAAAAgBQAAAAAAAAIACgCIABgDIACgCQAAAAABAAQAAAAABAAQAAAAABAAQAAAAAAAAIACgDIABgBIABgCIABgBIAEgCIAAACIgEAFIgGAHIgDADIgCABIgCABIAAAAg");
	this.shape_46.setTransform(-47.5,41,0.354,0.354);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFFFF").s().p("AgCADQAAgDACgCQABAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAAAIABABIgDABIAAACIgBABIgBAAg");
	this.shape_47.setTransform(-47.5,40.6,0.354,0.354);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFFFF").s().p("AAAAGQAAAAAAAAQAAgBAAAAQAAAAAAgBQgBAAAAAAIgCgCIgBgCIgBAAIABgCIABgCIACgBQAFAAACAFQAAADgEADg");
	this.shape_48.setTransform(-40.1,31.3,0.354,0.354);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFFFF").s().p("AA/FrIgHgBQhMACgxgLQgMgBgNgHQgEgDgHACQgIADgEgBIgLgEIgMgEIgSgFIgJgEIgegLQgIAAgEgCQgbgKgFgFQgGgEgOgCQgHgBgogcQgtgfgVgYQgMgIgGgOIABgDQAAgBAAAAQAAgBAAgBQgBAAAAAAQAAgBgBAAIgKgHQgEgDgEgIQgEgKgDgDQgPgHAAgMQABgHgHgOQgGgMAAgFQABgCgFgKIgDgDQgCgDABgDQAAgDgBgHQgCgGACgDQABgFgEgJQgGgLABgJIACgJQABgGgDgEQgCgBABgEIAAgEQAEgIgEgHQgCgDAAgEQAAgFAEgBQADgBACgGIABgIQAFgHgBgDQgBgFAEgIIAFgIQAFgVAGgGQAFgEABgGIAAgFIAIgKIAGgOIARgZQAEgGATgUQAVgVAFgEQASgLAMgLIAZgSQAUgOAFgCQALgEAKgLIAFgCQABAAABAAQAAgBABAAQAAAAAAAAQAAgBAAAAQABgCAUgIIAagKIAOgFIAPgHQAIgEBcgYQApgGAoAGIAJAAQAJAAASAEIAWAFIALAGQAJAFAJgBQAJgBAGACIAHADQALgBAOAFQALAFACgBQAKgGAJAJQAIAJAYACQADABALAHQALAHANADIAPAJQAOAJAIACIASANIASANQANAFAHALQAEACAIAIQAJAIABAEIANAOQAIAJAFAEQAeAXAGAPQAFAJgDALQABADAEABIAHACQAEABADAFQADAFgCAHIgDADQAAABAAAAQgBABAAAAQAAAAAAABQAAAAAAABQACAFgCALQgBAIAEAEQAHAHACAXIACAaQACASgGAdIgGAeQgDAOgCADQgCACgCAJIgBAGQAAAEgCABQgDAAgCADIgCAFQgMAdgKALQgGALgFACIgEABIgCAEIghAkQgGAFAAgBIACgEIABAAIACgBIACgDIACgDIAEgFIAFgEIACgDIAEgCIADgEIACgIIAFgHIACgDQAAgBAAAAQAAAAAAgBQgBAAAAAAQgBAAgBABIAAABIgEAEIgCADIgEACIgCACQgBAAAAgBQAAAAAAAAQAAAAAAgBQAAAAAAAAIACgEIACgBIAEgGIABgBIABgBIABgCQAAgBAAAAQAAAAAAAAQAAAAAAAAQgBAAAAAAIgDACIgLAMIgCABIgCABIAAAAIgBAAIAAABIgBAAIgBgBIACgCIABgBIAAgBIACgBIADgDIAAgDIABgBIABAAIAAgCIACgBIABAAIAAgCIAAgBIADgFQABgBABAAQABAAAAAAQABgBAAAAQAAAAAAAAIAAgCQABgBAAAAQABgBAAAAQABgBAAAAQAAAAAAgBIAAgBQAAgBAAAAQAAAAgBAAQAAAAAAAAQgBAAgBABIgEACIgCACIgCABIgDACIgEAFIgCAAIgBgBIgBABIgBABIgBAAIgBgBIgBAAIgBABIgCAAIABgDIAAgBIABgBIACAAIACgFIAEgCIADgFIACgEQABgBABAAQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAAAQAAAAgBAAQAAAAgBABIgBACIAAACIgBACIgBADQgFABgBABIgBADQgBAEgCACIgFADIgDACIgCACIgCgBIgCgBQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAAAIABACQAAAAAAABQAAAAgBABQAAAAgBAAQgBAAgBAAIgBgBIABgCQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAAAgBABIgBACIgCgBQAAAAgBAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAAgEIABgBIABgBIABAAIADACIAAgCIABgBIADgBQAEgDAAgDIgCgCQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIADgCIACgBIAEgCIABgEQABAAAAgBQAAAAAAAAQAAgBgBAAQAAAAgBAAIgBAAIgCAAIgEgBQAAAAAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAIABgDQAAAAAAgBQAAAAAAAAQgBgBAAAAQAAAAgBAAIAAAAIgCABIgDADIgBADIABABIAAABQABABAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgGgCIgCABIgBACIABADIAAABIgCABIgGAAQAAgBAAAAQgBgBAAAAQAAAAAAAAQgBAAAAAAIgCABIAAACIAAABIgBACIAAABQAAABAAAAQAAAAABABQAAAAAAAAQABAAAAABIABACIgBABIAAADIgBABIgDAAIgDABQAAAAgBAAQAAAAgBAAQAAABAAAAQAAAAgBAAIgBADQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAIgDABIgCACQgDACACgEQABgDADgDIABgCIABgDIAEgEIACgDIACgDIALgNIAEgEIABgCQABAAAAAAQAAAAgBgBQAAAAAAAAQAAAAgBAAIgCAAIAAgCQAAgBAAAAQAAgBAAAAQAAAAAAgBQAAAAgBAAIgBABIgBABIgCAAIgDADIgHAGIgDACIgCADQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAQAAAAAAgBQAAAAAAAAQAAgBgBAAQAAAAAAAAIgCADIgCABIgDADIgEAFIgCADIgDABIgCADIgCADQAAAAgBAAQAAAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQABgBAAgBQAAAAAAgBIACgDIADgDIABgCIACgBIAEgEIAEgGQAHgHgCgBQAAAAgBAAQAAgBgBABQAAAAgBAAQAAAAgBABIgCABIgCABIAAACQAAAAAAAAQgBAAAAAAQAAABgBAAQAAAAgBAAIgDAEIgCABIgCABQgBAAgCAEIgHAEIgFADIgDADQgBAAAAAAQAAAAAAAAQgBgBAAAAQAAgBAAAAIABgFQgBgDACgCIADgDQAEgCAAgCQAAgBABAAQAAgBAAAAQAAgBAAAAQABAAAAAAIABgCIACgEQACgDACgBQABAAABAAQAAgBABAAQAAAAAAAAQABgBgBAAQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAAAgBIACgCQABgBAAAAQAAAAAAgBQABAAAAAAQABgBAAAAQABAAABAAQAAgBAAAAQAAAAABgBQAAAAgBAAQAAgBABAAQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAABAAQAAgBAAAAQABAAAAAAQAAgBAAAAQAAgEAFgBQACgBAAgEIABgIQAIgMACgHQAJgVADgPQACgJAAgLIgBgOQABgOgMggIgDgEQgCgKgIgIQgIgIAAgDQAAgEgCgCIgCgBQAAgGgDgBQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAgBAAAAIgJgMQgHgJgFABQAAAAgBAAQAAgBAAAAQAAAAgBgBQAAgBgBAAIgCgEQgxgmgQgGIgIgGQgFgEgEgBIgVgJQgSgJgFgBQgIAAgBgBQAAgBAAAAQAAAAAAgBQAAAAgBAAQAAgBgBAAQgQgFgHACQgIADgGgGQgBgBgIgBQgGAAAAgBQABgBAAAAQAAAAgBAAQAAAAAAAAQAAAAgBAAIgDABQgXADgBgEQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAAAgBAAIgFACIgKgBQgEABgMgCQgIgBgEAEQgCABgMADQgLACgBACQgEAGgLACQgEAAgFADQgEADgGAAQgIAAgDABQgDABgEAFQgDACgFgBQgGgBgCACQgCADgCAAIgCgBQgVAFgDADQgEAFgbAJQgZAJgBACQAAABAAAAQAAAAAAABQgBAAAAABQgBAAgBABIgEABQgJABgHAIQgEAFgyAlQgNAHgGALQgCAEgIAHIgHAHQgBAFgEAEIgEAHIgHAUQgEAOgBAGQgCAqALAbQACAGADACQABABABAAQAAABAAAAQABABAAAAQAAABAAAAQABAGADAEIAGAGQACADACAHIAIALIAUAQQAPAMABACQABAHARAKIAfAQQAIAEAbALIAKAEQAMABADAEQACABAHAAIAKAAQAEACADgCQADgDACgKIACgOIgBgJQgBgJACgEQADgLAAgDQAAgHgCgJQgCgHACgDQAAgBAAAAQAAgBAAAAQAAgBAAgBQAAAAgBgBQgDgEgBgHIgEgVQgDgFgDgCIgEgCQgLgIgKgBQgHgBgKgIQgLgJAAgCQgBgDgEAAQgEgBgBgBQgCgJgFgEIgEgGIgDgEIgBgCQABAAAAgBQAAAAgBAAQAAAAAAgBQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQAAAAABgBIADgEIACgGIAIgGQAEgDADABIACABQABABAAAAQABAAAAAAQABAAABgBQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQABABAAAAIADABQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAAAIADACIACACIADAAIADABQAAACATAIQADABAKADIAFACQADABACACIADACIACgBIAFACQABABAIgBIAJACIADgBIACgCQABAAAAgBQAAAAAAAAQAAgBgBAAQAAgBgBAAIgCgEIgDgFQgCgHgBAAQAAAAgBAAQAAAAAAgBQAAAAAAAAQgBAAAAAAIgBgDIgDgPQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBgBAAQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAgBAAAAIABgJQAAgGgDABQAAAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAgBQgDgSAHgDIADgDIADgBIAGgBIAQgFQABAAAAAAQAAgBAAAAQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABAAAAgBQABAAAAAAQAGgCABABIABABQAAADAFgCQAMgCANADQANAEAHAGIAHAGIADACQAAABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAABQAAABABAAQAAAAAAABQAAAAAAAAIADAAQAAABABAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAAAAAABQAAAAAAAAIADAHQACAEgCADQgCADACADQADAEgBACQgDAGAAAGQAAAAABABQAAAAAAABQABAAAAAAQABAAAAAAQABAAABAAQAAAAABAAQAAAAAAAAQABAAAAgBQABgCAHgBQADgBAGgFIACgDIADABQAAAAABAAQAAABABgBQAAAAABAAQAAAAAAgBQABAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBQAAgCADgFIAEgCQABgBAAAAQABgBAAAAQAAgBAAgBQAAAAAAgBIACgCIAOgTQALgLAIABQAKAAACALQADAHgCgBQgFAAAAAFIAAAPIABAFQAAAAABABQAAAAAAABQABAAAAABQAAAAgBABIgCAEQgDACgBAFIgDAJQgDAHgBAAQgDACgBAEQgBAEgCABIgUAYQgDAEgCAAQgDgBgHAGQgNAJABAEIADADIADACIAGAAIACABQAEABADADIADABIATABQAIACAHAAQABAAABAAQABAAAAABQABAAAAAAQABAAAAABIABABIAGgBIANABIAOACQAMABAFACIALABIAAACIAAAAIAGAFQABAEgDADIgCAFIABAFIgBAEQABAFgEAEIAAADQgDADgKAEQgHADgKgBQgsgFgDgCQgDgEgBABIgBACQgKAAgEgBQAAAAAAAAQgBgBAAAAQAAAAgBAAQAAgBgBAAQAAgBAAAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAABQAAAAgBAAQAAAAgBAAIgNABQgLgBgGABQAAAAAAAAQgBAAAAAAQgBAAAAABQgBAAAAAAQgEACgGAAIgIABQgHAEgEABQgLADgDAUIgBAFIgDAFIgBACIgDATQgEAQABAKQAAAEAGADQAEAFAIABIAUACQAKAAABABQABAAAAAAQABABAAAAQAAAAABAAQAAgBAAAAIACAAIADADIAEAAQACgBAUAAIAigCIARgEQAKgBACABIAFAAIACgCQABgBAAAAQAAAAABAAQAAAAAAABQABAAAAAAIADAAIACgBIACABIACAAQABAAAAABQABAAAAAAQABAAAAAAQABgBAAAAIADgBQAAAAABAAQAAAAAAAAQAAAAAAABQAAAAgBAAIgBACQAAAAABAAQAAAAAAAAQAAABABAAQAAAAABAAIACgEQAAAAABAAQAAgBAAAAQABAAAAABQABAAAAAAQAAABABAAQAAAAAAABQAAAAABAAQAAAAAAAAQAFAAABgDIADgCIAHAAIACABIACgBIAFAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAIADgDIAFgBIAFgCIAEgDIADgCIABgCQAAgBAAAAQAAAAABAAQAAAAAAAAQAAAAAAAAIAEADIAEgDIADgDIAFAAQAAAAABAAQAAAAAAABQAAAAgBAAQAAAAgBABIgCACIgCAAIgEACQgFABACADQAAAAAAABQABAAAAAAQAAAAABAAQAAAAABAAIADgBIAAgCQAAgBAAAAQAAAAAAAAQABAAAAAAQAAAAAAAAQABAAAAAAQAAAAABABQAAAAAAABQAAAAAAABQABAAAAABQABAAAAAAQABAAAAAAQABAAABAAIADAAQABAAAAAAQAAAAABAAQAAAAAAAAQAAABgBAAQAAABAAAAQAAAAAAABQgBAAAAAAQgBAAgBAAQgEABgCACIgCADIgEABQAAABAAAAQAAAAAAABQABAAAAAAQAAAAAAABIADABQAAAAABAAQAAgBABAAQAAAAABgBQAAAAABgBIAFgEQAAgBABAAQAAAAABAAQAAABABAAQAAAAAAABQABAAAAAAQAAABAAAAQAAABAAAAQAAABgBAAIgBABIgFADIgGAAIgCADQABABAAAAQAAAAABABQAAAAABgBQABAAABgBIADgBIABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAgBABAAIAEgEQADgCADAAIACABQABAAAAABQAAAAAAAAQAAABAAAAQAAAAgBABIgDAAQAAAAAAAAQgBABAAAAQgBAAAAABQgBAAAAABIgDADQAAAAAAABQAAAAAAAAQAAAAAAABQAAAAAAAAIADgCQAFgDACACIAAACIgCACIgBAFIgEABIgDADIgCACIAAACIgCACIAAABQAAAAAAABQAAAAABABQAAAAABAAQABAAABAAIADgBQAAAAABgBQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABQAAAAAAAAQgBABAAAAQgBAAgBABQAAAAAAAAQAAABAAAAQAAABABAAQAAAAABABQAAAAABAAQAAAAABAAQAAgBABAAQAAAAAAgBIABgBIABgCIAFAAIAFAAQAGgCADgEIACgCQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAQABAGACACQAEADADgBIACgCIABgCIADgCIADAAIAEgCIAGgCIAEgCIACAAIACAAIABgBIAAgBIABAAIABgBIADgCQABAAABAAQAAAAAAABQAAAAABAAQAAABgBAAIAAABIACACIgBABQAAABAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgCgCIgDAAQAAAAgBAAQAAABAAAAQgBABAAAAQAAAAAAABIABACQABAAAAAAQAAABAAAAQAAAAAAABQAAAAgBAAIgBACIgBABIgBgBIgBABIgBACIgBABIgIAGIgCACIgHAEQgEADgCADIghAbIgUAMQgOAMgJAEQgCAAgFAEIgKAEQgLAGgSAFIgdAIIgVADQgOADgGAAIgNABIgFAAg");
	this.shape_49.setTransform(-56.5,35.5,0.354,0.354);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FFFFFF").s().p("AgpA4IAAhfQAAgQAPAAIAFAAQAPAAAAAQIAABBIAgAAQAQAAAAAOIAAABQAAAPgQAAg");
	this.shape_50.setTransform(15.3,45.7,0.354,0.354);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFFFFF").s().p("AAaA4IgJgXIgjAAIgJAXIgiAAIAohmQADgJASAAQASAAACAJIAqBmgAgMAIIAWAAIgKgfg");
	this.shape_51.setTransform(11.1,45.7,0.354,0.354);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#FFFFFF").s().p("AAkA4QgHABgCgCIgHgGIgngzIAAA6IggAAIAAhfQgBgQAOAAIAEAAQAGAAADACIAHAGIAmAyIAAg5IAhAAIAABeQAAARgPgBg");
	this.shape_52.setTransform(6.5,45.7,0.354,0.354);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#FFFFFF").s().p("AgpAqQgRgRAAgZQAAgYARgRQARgQAYAAQAaAAAQAQQARARAAAYQAAAZgRARQgQAQgaAAQgYAAgRgQgAgQgTQgHAIAAALQAAAMAHAHQAHAIAJAAQALAAAHgIQAHgHAAgMQAAgLgHgIQgHgIgLAAQgKAAgGAIg");
	this.shape_53.setTransform(1.8,45.7,0.354,0.354);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#FFFFFF").s().p("AgQA4IAAhhQAAgOAPAAIADAAQAPAAAAAOIAABhg");
	this.shape_54.setTransform(-1.7,45.7,0.354,0.354);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#FFFFFF").s().p("AgQA4IAAhRIgTAAQgQAAAAgPIAAAAQAAgPAQAAIBGAAQARAAAAAPIAAAAQAAAPgRAAIgSAAIAABRg");
	this.shape_55.setTransform(-4.8,45.7,0.354,0.354);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#FFFFFF").s().p("AAaA4IgJgXIgjAAIgIAXIgjAAIAohmQADgJASAAQASAAACAJIAqBmgAgMAIIAWAAIgKgfg");
	this.shape_56.setTransform(-9.1,45.7,0.354,0.354);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#FFFFFF").s().p("AAjA4QgFABgEgCIgGgGIgngzIAAA6IghAAIAAhfQABgQAOAAIADAAQAFAAAEACIAHAGIAmAyIAAg5IAgAAIAABeQAAARgOgBg");
	this.shape_57.setTransform(-13.7,45.7,0.354,0.354);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#FFFFFF").s().p("AAGApIgOgVIgGAAIAAAkIgjAAIAAhcQAAgTASAAIAgAAQAvAAAAAlQAAAYgYAHIAZAfQACACgGAEQgGAGgKAAQgMAAgLgPgAgPgCIAPAAQANAAAAgNQAAgNgOgBIgOAAg");
	this.shape_58.setTransform(-18.1,45.7,0.354,0.354);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#FFFFFF").s().p("AgbA4QgSAAAAgSIAAhKQAAgTASAAIBJAAIAAAeIg4AAIAAAMIApAAIAAAaIgpAAIAAANIA4AAIAAAeg");
	this.shape_59.setTransform(-22.4,45.7,0.354,0.354);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#FFFFFF").s().p("AgQA4IAAhRIgTAAQgQAAAAgPIAAAAQAAgPAQAAIBGAAQARAAAAAPIAAAAQAAAPgRAAIgSAAIAABRg");
	this.shape_60.setTransform(-26.5,45.7,0.354,0.354);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#FFFFFF").s().p("AAkA4QgGABgDgCQgDgCgEgEIgngzIAAA6IggAAIAAhfQgBgQAOAAIAEAAQAJgBAHAJIAmAyIAAg5IAhAAIAABeQAAARgPgBg");
	this.shape_61.setTransform(-30.9,45.7,0.354,0.354);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#FFFFFF").s().p("AgQA4IAAhhQAAgOAPAAIADAAQAPAAAAAOIAABhg");
	this.shape_62.setTransform(-34.3,45.7,0.354,0.354);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#FFFFFF").s().p("AB8DDQgVAAgLgGQgIgEgNgQIiMi1IAADMIhvAAIAAlLQgBgbANgOQANgOAXAAIAMAAQATAAALAGQAKAGANAQICJCyIAAjLIBvAAIAAFLQAAAbgMAOQgNAOgXAAg");
	this.shape_63.setTransform(10.3,32.9,0.354,0.354);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#FFFFFF").s().p("ABaDCIgghQIh6AAIgfBQIh3AAICKliQAFgQAPgHQASgKAmAAQAjAAARAKQAOAHAFAQICQFigAgsAcIBQAAIgnhug");
	this.shape_64.setTransform(-4.3,32.9,0.354,0.354);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#FFFFFF").s().p("AiQDCIAAlLQAAg4AyAAIARAAQA0AAAAA4IAADjIBzAAQA3AAAAAyIAAABQAAA1g3AAg");
	this.shape_65.setTransform(-17.1,32.9,0.354,0.354);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#FFFFFF").s().p("AilDAIAAk9QAAggAPgRQAQgRAeAAIBmAAQBRAAArAjQAsAkAABFQAACHimAAIgtAAIAABsgAgvgBIArAAQA2AAAAgyQAAgYgPgNQgOgNgaAAIgqAAg");
	this.shape_66.setTransform(-29.3,32.9,0.354,0.354);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#004EB6").s().p("A0LIUQgLgGgFgFQgFgFgJgCIgQgDQgGgCgDgCIgGgHQAAAEgHAEQgGAFAAADIgBABIgDAAQgSgDgIgJQgIgJgCgSQABgEgBgCQgBgDgGABQgEABAAgFQABgEACAAQAGgCAGgIQAGgIAFgDQABAAAAgBQABAAAAgBQABAAAAgBQAAAAgBAAIgFgDQgggRAegWQAFgEABgFQAAgFgGgCQgKgEAFgLIAEgHQABgDgFgEQgBAAAAAAQAAgBAAAAQgBAAABgBQAAAAAAgBQACgCADgBQAWgFgQgUQgPgPANgIQAEgDAAgCIABgGIgCgUQgDgNABgIQABgCgDgDQgKgGABgGQACgFAJgGQgLgIgBgLQgCgKAIgJIACgCQgEgJAFgPQAHgSgBgHQAAgHgIgPQgHgNACgJIABgHQAAgEAFgCQAGgCgEgHQgHgNARgDQgSgLAMgOQAGgHgGgGQgQgNAOgOIACgBIAAgCQgFgOAEgVIAFgiQAAgJgIgSQgHgQACgKQACgFgHAAQgBAAgBAAQAAAAgBgBQAAAAgBAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAAAAAAAQAAgBAAAAQAGgCADgHQADgIAEgCQALgGABgGQACgFgJgIIgGgFQgBgCAIgEQAJgEABgOQAAgNgIgIQgIgJAIgJQAEgGABgDQAAgEgGgEIgEgDQAHgGgGgMQgGgNAIgHQAFgFgCgPQgCgQAHgHQAAgBABAAQAAgBAAAAQAAgBAAAAQgBgBAAAAIgFgDQgEgIAAgDQABgFAKgBIAFABQADgBAAgEQAAgKgFgBQgGAAgBgEIAAgHQABgFAEAAIAIAAQAPABAHgCQAKgEABgNQABgEAEAAIAHABQBogFBAABIAegCQASgCAMADQACABAJgFQAIgFAGABQAEABAGAAQAGAAADAGQACAEAKAAQAJAAACgDQAEgFAHAAIAKAAIA1ABQAFAAACgDQAEgFAFAAQAFAAADAGQAEAIAHgEQAOgHAXABIAmAAIARAAQAKAAAGgFQADgCAEAAQAFAAADADQAHAGACAAQAGABAEgIQACgCAEABQAEABACADQAHALAJgKQACgCADAAIAGAAIA1AAIAGABQADAAABgEQAAgDAEgBQAAAAABAAQABAAAAAAQABAAAAABQABAAAAAAQALAHASgEQAVgGAIACQAOAEATAAIAiAAIAPAAQAIAAAGgGQAAAAAAAAQAAAAABgBQAAAAABAAQABAAABAAQAAAAABAAQABAAAAAAQABAAAAAAQAAAAABABQAIAHAOgEQAQgFAFABQAMADApABIAJAAQAGgBABgGQABgEAQACQAPABAEAEQAGAGAJAAQAKAAAGgGQACgCADAAIAGAAIAXAAQAOAAAKACQAMACACAAQAJAAAFgJQAEgGAaAFQANADAKgBQAXgBAtADQAtACAWAAIAKAAQAFgBABgGQAAgBABAAQAAgBAAAAQABgBAAAAQABAAAAAAQADABADACQAHAHAEAAQAFAAAFgGIADgCIACABQAGABAOgBQANABAGAJIADABIACAAQAKgKASABIAdACIAWABQAOABAFgCQAJgEAFABQAFAAAGAFQAAAAABABQAAAAABAAQAAAAABAAQABAAABAAIADgCQAFgIACAAQADgBADAJIAEABIADAAQAHgLAPAAIAYADQAeADAqABIBIADIAxACIALAAQAGgBACgHQABgCAGAAQAGgBADAGQADAFAFABQAFABAFgEQAJgHAEABQAFABAGAJIAMgJQAIgEAGAMQACACAEABQAFABAEgDQAYgOAOAQQADAEAFgDQANgJARAAQARAAALAIQADACADgBIAFgDQASgJACAOQABAEAEABIAGAAIB4AAIAEAAQAGgGAJABIARABIAJABQAGgBAAgHQAAgCAFAAQAFAAACABQATAKARgNQAEgDADADQAFAEAGgBQAFgBAEgFQABgCAIgBQAIgBAAACQACAFAHAAQAIAOAFgGQADgDACgJQAHgPAUAKQAOAFAGgEQAPgJAWgDIAmgBIBPgHQAygFAdgCQAIAAAAgCQACgMANAAQAUAAACgBIAWgHQAYgIAsADQAEAAAAAEIAAAGQABACAEgBQABgBABAAQAAAAABAAQABABAAAAQAAABABABQABAEgFABIgFABQAAAHgJAIQgKAJgBAEQgEAWAJAJQANAMgIAUQgCAHAAAMQgBADADAQQACAMgGAIQgEAFAAAFQAAAJAMAAQACAFgBACQgCAGgFAcIgDASQABAGAIAKIACAGQAAADgBACQgEADgCAKQgCAJgFAEIgBABQgEAEAHAGQAHAFgDAEQgJANANAGQAAAAABAAQAAAAAAABQABAAAAAAQAAABABAAQAAABAAAAQAAAAAAAAQAAABAAAAQAAAAAAAAQgIAEABALQABAMgGADIgBAEQAKACAAAIIABAOQACACgBADQgBAEgFABQgFACACAIIAEAXQABAMgDALQAAACACAHIAFALQAEANgCAQIgEAbQgBAJAFAbIACAJQgBAFgHACQgDABACAJIAIAlQADAWgDAPIAAAbQAAAQgKAJQgBADAAAGQABAHAFABQAEACACADIABAFQAFARgOAHIgFAEQgCACAHABQADABABACIABAEQABAFgEAJQgCAJAIAFQABAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQgBAEgCAAQgLABgCAGIABAMQABALgGAHQgDAEABAHQAAAHAHAFQAGAGACAKQABAJgEAHQgEAJAAAHIgDAYQgDAPAEAJQAAADgIADQgIADgDgBQgIgDgJABQgJACgBAFQgDAGgEACIgKABQgjAAgTACQgKACgTgDQgUgCgKAAIgRACQgKACgGAFIgFADQgEABgDgFQgDgDgRAAQgRAAgEADQgKAIgGABQgFAAgSgFQgGgCgGAAQgKABgDAIQgDAHgIgBQgGAAgWADIgKABQgGgBgEgGQgDgFgKACQgMAEgFAAQgLACgCgBQgFgBAAgJQABgHgOAAIizAAIgIAAQgEABABAFQAAAHgEACQgDABgIgBQiegDhPgGQgIgBgEAAQgHABgDAHQgBAEgIAAQgJAAgEgEQgHgIgJAAQgHAAgKAFQgDACgCgBQgPgIgGAAQgFAAgRAIQgGADgGAAQgIgBgEgFQgDgFgGgBQgEAAgDACQgIAGgOAAIgVgBQgFABgCgEQgCgGgDgBQgFAAgHADQgHAEgDAAQg2ABgogCIgLgBQgHgBgEgFQgCgDgEADQgFAFgCAAIgfABQgTAAgMgCQgigFgpAEQgXAFgMAAIgLAAQgFgBgCgFQgCgDgDgBQgBAAgBAAQgBAAAAABQgBAAAAABQAAAAAAABQAAAJgHAAIgKgDQgMgCgRAAIgdAAIgGAAQgDAAgCADQgHAIgCgKQgFgBgBABQgLAHgTgBIgggBQgHABgBgFQAAgFgFgBQgEAAgDABQgJAHgOgBIgXAAIgKAAQgGABgCAFQAAABgBAAQgBABAAAAQgBAAAAAAQAAAAgBAAQgNgIgWAEQgaAFgKgDQgGgBgBAGQgDAJgGgIQgGgHgBAAQgDgBgCAGQgCAFgDAAIgHgBQg6gGgiAGQgkAGgagCQgwgFgaAEQghAFgbAAIgQAAQgJAAgGgDQgCgBgEABIgGABQgJAJgPAAQgSgCgIAAIgPgBQgIgBgGAFIgEABQAAAAgBAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQgGgJgGAJQgCADgEgBQgLgEgSACQgVAEgIgCIgagHQgQgDgMACQhUAMgsgBQgPALgZABQgcAAgOACQgSADgZABIgrABQgGAAgMgGg");
	this.shape_67.setTransform(-27.9,36,0.354,0.354);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer 2
	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#FFFFFF").s().p("A3cEWIAAoxMAu5AAEIAAIzg");
	this.shape_68.setTransform(62.7,36.8);

	this.timeline.addTween(cjs.Tween.get(this.shape_68).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-87.4,8.4,300.2,56.9);


(lib.mrUWcopy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D6D6D6").s().p("AAHAiQgGAAgBgBQgDgCgBgDIgBgHIAAgeIgJAAIAAgJIAJAAIAAgPIAJAAIAAAPIALAAIAAAJIgLAAIAAAbIAAAEIACACIAEABIADAAIACAAIAAAJIgEAAIgEAAg");
	this.shape.setTransform(103.1,30.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#D6D6D6").s().p("AgOAbIAAg0IALAAIAAALIAAAAQABgDACgDIAEgEIAHgCIADAAIABAAIAAAMIgCgBIgDAAQgEAAgDACQgDACAAAEQgCAFAAADIAAAag");
	this.shape_1.setTransform(100,31.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#D6D6D6").s().p("AgMAYQgGgDgDgHQgDgGAAgIQAAgGADgGQADgHAGgEQAGgDAGgBQAGABAFACQAFACADAFQAEAEABAGQABAFAAAEIglAAQAAAFABADQACAEADACQADACADAAQAFAAADgCQADgCACgFIALAAQgBAGgEAEQgDAEgFADQgFABgGAAQgGABgGgEgAANgDIgCgHIgEgGQgDgCgEAAQgDAAgDACQgDADgBADQgCACAAAFIAZAAIAAAAg");
	this.shape_2.setTransform(95,31.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#D6D6D6").s().p("AAKAkIgPgaIgHAHIAAATIgLAAIAAhHIALAAIAAAoIAUgUIAOAAIgUASIAWAhg");
	this.shape_3.setTransform(89.7,30.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#D6D6D6").s().p("AgMAYQgGgEgDgGQgDgGAAgIQAAgGADgGQADgHAGgEQAGgDAHgBQAGAAAFACQAFADAEAEQADAEABAGIgMAAQgBgEgDgDQgDgCgFgBIgFACQgDABgCAFQgDAEAAAGIABAIQACAFADADQADACADAAQAFAAAEgDQADgDABgGIAMAAQgCALgGAFQgGAGgLgBQgGABgGgEg");
	this.shape_4.setTransform(83.7,31.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#D6D6D6").s().p("AgEAkIAAgzIAJAAIAAAzgAgEgYIAAgLIAJAAIAAALg");
	this.shape_5.setTransform(79.5,30.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#D6D6D6").s().p("AAOAkIgOg2IgOA2IgNAAIgThHIAMAAIAOA2IAPg2IALAAIAOA2IABAAIANg2IANAAIgUBHg");
	this.shape_6.setTransform(73.5,30.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#D6D6D6").s().p("AALAkIAAghQAAgEgCgDQgDgDgFAAQgCAAgDACQgDACgBADQgCABAAAEIAAAfIgMAAIAAhHIAMAAIAAAbQACgEAEgCQAEgCAEAAQAJAAAFAEQAFAFAAAHIAAAkg");
	this.shape_7.setTransform(62.8,30.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#D6D6D6").s().p("AgMAYQgGgEgDgGQgDgGAAgIQAAgGADgGQADgHAGgEQAGgDAHgBQAGAAAFACQAFADAEAEQADAEABAGIgMAAQgBgEgDgDQgDgCgFgBIgFACQgDABgCAFQgDAEAAAGIABAIQACAFADADQADACADAAQAFAAAEgDQADgDABgGIAMAAQgCALgGAFQgGAGgLgBQgGABgGgEg");
	this.shape_8.setTransform(57,31.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#D6D6D6").s().p("AgEAkIAAgzIAJAAIAAAzgAgEgYIAAgLIAJAAIAAALg");
	this.shape_9.setTransform(52.8,30.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#D6D6D6").s().p("AgOAbIAAg0IALAAIAAALIAAAAQABgDACgDIAEgEIAHgCIADAAIABAAIAAAMIgCgBIgDAAQgEAAgDACQgDACAAAEQgCAFAAADIAAAag");
	this.shape_10.setTransform(50.1,31.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#D6D6D6").s().p("AgEAkIAAhHIAJAAIAABHg");
	this.shape_11.setTransform(46.7,30.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#D6D6D6").s().p("AgOAiQgHgDgEgHQgEgGAAgJIAAgtIANAAIAAApIAAAHQABAEACADQABADAEACQADACAFAAQAGAAADgCQAEgCABgDIACgHIABgHIAAgpIANAAIAAAtQAAAJgEAGQgEAHgHADQgGADgJAAQgIAAgGgDg");
	this.shape_12.setTransform(41.7,30.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#D6D6D6").s().p("AADAQIAAgQQAAgCACgEQACgEADgCQAEgDAEAAIAAAHQgEABgBADQgCACAAACIAHAAIAAAQgAgRAQIAAgQQAAgCACgEQACgEADgCQADgDAFAAIAAAHQgEABgCADQgBACAAACIAHAAIAAAQg");
	this.shape_13.setTransform(87,9.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#D6D6D6").s().p("AgHAlIAAgQIAPAAIAAAQgAgCAPIgEgfIAAgUIANAAIAAAUIgEAfg");
	this.shape_14.setTransform(83.1,11.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#D6D6D6").s().p("AgLAkQgFgCgEgEQgDgDAAgHIAOAAQABAFADABQADACACAAQAGAAAEgEQACgEAAgGIAAgHQgDAFgEACQgFACgDAAQgHAAgFgEQgFgEgDgGQgCgEAAgIQAAgHACgGQADgGAFgEQAFgDAIgBQADAAAEACQAEADADAEIAAgHIAPAAIAAAxIgCAHQgBAEgDAEQgCAEgGACQgFADgIAAIgLgCgAgFgXIgFAGIgBAHIABAIQACACADACQACACADAAQAEAAACgCQAEgCABgBIABgIIgBgIQgBgEgDgCQgCgCgFAAQgDAAgCACg");
	this.shape_15.setTransform(78.4,13.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#D6D6D6").s().p("AAKAcIAAgdQAAgHgCgDQgCgEgGABQgDgBgDAEQgDAEAAAHIAAAcIgPAAIAAg1IAPAAIAAAHQADgEAEgCQADgDAFAAQAHABAEADQAFACACAGQABAFAAAGIAAAgg");
	this.shape_16.setTransform(72.1,12.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#D6D6D6").s().p("AgQAZQgEgDgCgFQgCgFAAgHIAAggIAPAAIAAAeQAAAGADAEQABADAFgBQAEABAEgEQACgEAAgIIAAgbIAPAAIAAA1IgOAAIAAgIIAAAAQgEAFgEACQgDACgEAAQgIAAgEgCg");
	this.shape_17.setTransform(65.9,12.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#D6D6D6").s().p("AgXAbIAAgLIAageIgYAAIAAgMIArAAIAAAMIgaAeIAcAAIAAALg");
	this.shape_18.setTransform(60,12.7);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#D6D6D6").s().p("AAJAjIgJgBQgCgBgCgDQgDgDAAgFIAAgeIgJAAIAAgKIAJAAIAAgQIANAAIAAAQIALAAIAAAKIgLAAIAAAZQAAAEABABQACABAEAAIABAAIADAAIAAAMIgEAAIgEAAg");
	this.shape_19.setTransform(55.4,12);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#D6D6D6").s().p("AgQAjQgEgDgCgFQgCgFAAgHIAAgfIAPAAIAAAdQAAAGADAEQACADAEAAQAFAAACgEQADgDAAgJIAAgaIAPAAIAAA0IgOAAIAAgHIAAAAQgDAEgFADQgDACgEAAQgIAAgEgDgAADgYIAAgNIAPAAIAAANgAgQgYIAAgNIAOAAIAAANg");
	this.shape_20.setTransform(50.5,11.8);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#D6D6D6").s().p("AAIAjIgIgBQgCgBgDgDQgCgDAAgFIAAgeIgJAAIAAgKIAJAAIAAgQIANAAIAAAQIALAAIAAAKIgLAAIAAAZQAAAEACABQABABADAAIADAAIACAAIAAAMIgEAAIgFAAg");
	this.shape_21.setTransform(45.5,12);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#D6D6D6").s().p("AgKAaQgGgBgEgFQgDgEgBgHIAOAAIACAFIAEADIAEABIAEAAIAEgDQABAAAAgBQAAAAAAAAQABgBAAgBQAAAAAAgBQAAgDgFgCIgKgDIgJgDQgDAAgDgCQgCgDAAgFQAAgGADgEQAEgEAFgCQAFgBAFAAQAFAAAFACQAGABADAEQADAEABAGIgOAAQAAgEgDgCQgDgBgDAAIgDAAIgDACIgCADQABADACABIAFACIAHACIAJADQAEABACABQACADABAFQgBAHgDAFQgEAEgFABQgGACgGAAQgFAAgFgCg");
	this.shape_22.setTransform(40.8,12.7);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#D6D6D6").s().p("AgOAGIAAgLIAdAAIAAALg");
	this.shape_23.setTransform(89.6,1);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#D6D6D6").s().p("AgQAbIAAg0IAPAAIAAAKIACgFQACgDAEgCIAHgCIACABIABAAIAAAOIgCAAIgDAAQgGAAgDACQgDADAAADQgBAEAAADIAAAYg");
	this.shape_24.setTransform(86.3,1.1);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#D6D6D6").s().p("AgNAZQgGgEgDgGQgEgHAAgIQAAgHAEgGQADgGAHgEQAGgEAGAAQAHAAAFADQAFACAEAFQADAEABAGQACAGgBAEIglAAQABAHADAEQADADAFAAQAEAAADgCQADgCABgDIANAAQgDAKgGAEQgHAEgJAAQgHAAgGgDgAALgEQgBgGgCgDQgDgDgFAAQgDAAgDACIgEAFIgBAFIAWAAIAAAAg");
	this.shape_25.setTransform(81,1.2);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#D6D6D6").s().p("AAIAjIgIgBQgCgBgDgCQgCgDAAgGIAAgeIgJAAIAAgKIAJAAIAAgQIANAAIAAAQIALAAIAAAKIgLAAIAAAZQAAAEACABQAAACAEgBIADAAIACAAIAAALIgEABIgFAAg");
	this.shape_26.setTransform(76.1,0.4);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#D6D6D6").s().p("AAKAbIAAgcQAAgHgCgDQgCgEgGAAQgDAAgDAEQgDAEAAAHIAAAbIgPAAIAAg0IAPAAIAAAHQADgEAEgCQACgCAGgBQAHABAFACQAEAEACAEQABAGAAAGIAAAfg");
	this.shape_27.setTransform(71.1,1.1);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#D6D6D6").s().p("AgWAeQgJgHABgPIAAgtIAQAAIAAAtIABAIQABADADACQAEADAFAAQAFAAADgCQAEgCACgDQABgEAAgFIAAgtIARAAIAAAtQAAAPgJAHQgIAIgPAAQgOAAgIgIg");
	this.shape_28.setTransform(64.1,0.3);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#D6D6D6").s().p("AgNAZQgGgEgDgGQgEgHAAgIQAAgHAEgGQADgGAHgEQAGgEAGAAQAHAAAFADQAFACAEAFQADAEABAGQACAGgBAEIglAAQABAHADAEQADADAFAAQAEAAADgCQADgCABgDIANAAQgDAKgGAEQgHAEgJAAQgHAAgGgDgAALgEQgBgGgCgDQgDgDgFAAQgDAAgDACIgEAFIgBAFIAWAAIAAAAg");
	this.shape_29.setTransform(54.3,1.2);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#D6D6D6").s().p("AgQAbIAAg0IAOAAIAAAKIADgFQADgDADgCIAHgCIABABIACAAIAAAOIgDAAIgCAAQgGAAgDACQgDADAAADQgBAEAAADIAAAYg");
	this.shape_30.setTransform(49.7,1.1);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#D6D6D6").s().p("AAKAlIAAgfQAAgGgCgCQgCgDgGAAQgDAAgDADQgDADAAAIIAAAcIgPAAIAAhJIAPAAIAAAcIABAAQACgEAFgCQACgDAFAAQAHAAAEADQAFADACAFQABAFAAAEIAAAig");
	this.shape_31.setTransform(44.2,0.2);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#D6D6D6").s().p("AgHAlIAAhJIAPAAIAABJg");
	this.shape_32.setTransform(39.5,0.2);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#D6D6D6").s().p("AAKAbIAAgcQAAgHgCgDQgCgDgGgBQgDABgDADQgDAEAAAHIAAAbIgPAAIAAg0IAPAAIAAAIQADgFAEgCQACgDAGABQAHAAAFACQAEAEACAEQABAFAAAHIAAAfg");
	this.shape_33.setTransform(82.3,-10.4);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#D6D6D6").s().p("AgNAZQgGgEgDgGQgEgHAAgIQAAgHAEgGQADgGAHgEQAGgEAGAAQAHAAAFADQAFACAEAFQADAEABAGQACAGgBAEIglAAQABAHADAEQADADAFAAQAEAAADgCQADgCABgDIANAAQgDAKgGAEQgHAEgJAAQgHAAgGgDgAALgEQgBgGgCgDQgDgDgFAAQgDAAgDACIgEAFIgBAFIAWAAIAAAAg");
	this.shape_34.setTransform(76.1,-10.4);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#D6D6D6").s().p("AAKAlIAAgfQAAgGgCgCQgCgDgGAAQgDAAgDADQgDADAAAHIAAAdIgPAAIAAhJIAPAAIAAAcIAAAAQAEgFAEgBQACgDAFAAQAHABAEACQAFADACAFQABAFAAAFIAAAhg");
	this.shape_35.setTransform(70,-11.4);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#D6D6D6").s().p("AgMAZQgGgEgEgGQgDgGAAgJQAAgGADgHQADgGAGgEQAHgEAGAAQAHAAAGACQAFACAEAFQADAFABAHIgPAAQAAgFgDgCQgDgDgFAAQgCAAgDADQgDADgBAEIgBAGIABAIQABAEADACQACADADAAQAFAAADgDQADgDABgFIAOAAQgBALgHAFQgHAGgLAAQgGAAgGgDg");
	this.shape_36.setTransform(63.9,-10.4);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#D6D6D6").s().p("AgQAYQgEgCgCgFQgCgFAAgHIAAggIAPAAIAAAeQAAAGADADQACADAEAAQAFABACgEQADgDAAgJIAAgbIAPAAIAAA1IgOAAIAAgHIAAAAQgDAEgFACQgDADgEAAQgIAAgEgEg");
	this.shape_37.setTransform(57.7,-10.3);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#D6D6D6").s().p("AgQAaQgEgBgCgEQgDgDAAgGQAAgGADgEQACgCAEAAQAFgCAEgBIAHgBIAHgBQACgCAAgDQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAgBAAAAQAAgBgBAAQAAAAgBAAQAAgBgBAAIgEAAQgDAAgDACQgCACgBAEIgPAAQABgHAEgEQAEgEAFgBQAGgCAEAAIAIABIAIACQAEABACAEQACADAAAEIAAAbIABAHIABAFIgQAAIAAgDIgBgCQgDADgFACQgCABgGAAQgFAAgEgCgAAEACIgFABQgEABgDACQgCABAAAEQAAAEACACQADABAEAAQACAAADgBIADgEIABgEIABgDIAAgGIgFACg");
	this.shape_38.setTransform(51.5,-10.4);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#D6D6D6").s().p("AgQAbIAAg0IAPAAIAAAKIABgGQADgCAEgCIAHgBIACAAIABAAIAAAOIgCgBIgDAAQgGAAgDADQgDADAAADQgBAEAAADIAAAYg");
	this.shape_39.setTransform(46.7,-10.4);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#D6D6D6").s().p("AgFAkQgEgCgDgFIAAAHIgOAAIAAhJIAPAAIAAAcIABAAQACgFAEgCQAEgCAEAAQAGAAAFADQAFADAEAHQADAFAAAJQAAAKgDAGQgEAHgFADQgFADgGAAQgEAAgFgCgAgGgEQgDADgBACQgCAEAAAEQAAAFACAEQABAEADACQADACADABQADgBAEgCQACgCABgEQACgEAAgFQAAgEgCgEQgBgCgCgDQgEgCgDAAQgDAAgDACg");
	this.shape_40.setTransform(41.3,-11.3);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#D6D6D6").s().p("AAKAcIAAgdQAAgHgCgDQgCgEgGABQgEgBgCAEQgDAEAAAHIAAAcIgPAAIAAg1IAOAAIAAAHQADgEAFgCQADgDAEAAQAIABAEADQAFACACAGQABAFAAAGIAAAgg");
	this.shape_41.setTransform(86.3,-22);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#D6D6D6").s().p("AgNAZQgGgEgDgGQgEgHAAgIQAAgHAEgGQADgGAHgEQAGgEAGAAQAHAAAFADQAFACAEAFQADAEABAGQACAGgBAEIglAAQABAHADAEQADADAFAAQAEAAADgCQADgCABgDIANAAQgDAKgGAEQgHAEgJAAQgHAAgGgDgAALgEQgBgGgCgDQgDgDgFAAQgDAAgDACIgEAFIgBAFIAWAAIAAAAg");
	this.shape_42.setTransform(80.1,-21.9);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#D6D6D6").s().p("AAKAlIAAgeQAAgHgCgBQgCgEgFAAQgEAAgDAEQgDABAAAIIAAAdIgPAAIAAhJIAPAAIAAAcIABAAQADgFADgCQADgCAEAAQAIAAAFADQAEADABAFQACAFAAAEIAAAig");
	this.shape_43.setTransform(74,-22.9);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#D6D6D6").s().p("AgMAZQgGgEgEgGQgDgGAAgJQAAgGADgHQADgGAGgEQAHgEAGAAQAHAAAGACQAFACAEAFQADAFABAHIgPAAQAAgFgDgCQgDgDgFAAQgCAAgDADQgDADgBAEIgBAGIABAIQABAEADACQACADADAAQAFAAADgDQADgDABgFIAOAAQgBALgHAFQgHAGgLAAQgGAAgGgDg");
	this.shape_44.setTransform(67.9,-21.9);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#D6D6D6").s().p("AgQAiQgFgFgCgGQgDgHAAgHQAAgIADgEQACgHAFgDQAGgEAIAAQADAAAEACQAFACACAEIAAgcIAPAAIAABJIgOAAIAAgHIAAAAQgDAFgEACQgFACgDAAQgIAAgGgEgAgGgEQgCADgCACIgBAIIABAIQABAEAEADQADACACABQAFgBACgCQADgDACgEIABgIIgBgIQgCgCgDgDQgDgCgEAAQgDAAgDACg");
	this.shape_45.setTransform(61.5,-22.9);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#D6D6D6").s().p("AgQAkQgEgCgDgDQgCgEAAgGQAAgGACgDQADgDAEgCQAEgCAFAAIAHgBIAHgCQACgBAAgBQAAgBAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAgBAAQAAgBgBAAQAAAAgBAAIgEgBQgDAAgDACQgCACAAAEIgQAAQABgGAEgEQADgEAGgCQAGgCAEAAIAIABIAIACQAEACABADQADADAAAFIAAAaIABAHIABAFIgQAAIAAgCIgBgDQgDAEgFABQgDACgFAAQgFAAgEgCgAADAMIgEABQgEAAgCACQgDACAAAEQAAAEADABQACACAEAAQACAAACgCIAFgDIAAgEIABgEIAAgFIgGACgAADgYIAAgNIAOAAIAAANgAgQgYIAAgNIAOAAIAAANg");
	this.shape_46.setTransform(55.4,-22.9);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#D6D6D6").s().p("AAZAlIAAgzIgTAzIgLAAIgSgzIgBAAIAAAzIgPAAIAAhJIAXAAIAQAyIARgyIAXAAIAABJg");
	this.shape_47.setTransform(47.6,-22.9);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#D6D6D6").s().p("AADAJQAEgBACgDQABgCAAgDIgHAAIAAgPIAPAAIAAAPQAAADgCAEQgBAEgEACQgDADgFAAgAgRAJQAEgBABgDQACgCAAgDIgHAAIAAgPIAPAAIAAAPQAAADgCAEQgCAEgDACQgEADgEAAg");
	this.shape_48.setTransform(40.4,-19.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer 2
	this.instance = new lib.mr_UW();
	this.instance.setTransform(-21.3,-30.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Wide textured block
	this.instance_1 = new lib.Symbol1copy();
	this.instance_1.setTransform(1.5,3.9,1,1,0,0,0,110.9,37.9);
	this.instance_1.shadow = new cjs.Shadow("rgba(0,0,0,1)",0,0,15);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-125.4,-50,257,111);


// stage content:
(lib.Plan_Maedchenhandel_300x250_DE_x_160427_vmi = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#1952A0").ss(1,1,1).p("A3WzcMAutAAAMAAAAm5MgutAAAg");
	this.shape.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(261));

	// Pointer
	this.instance = new lib.Tween1("synched",0);
	this.instance.setTransform(120.3,276.3,1.007,1.007);
	this.instance._off = true;

	this.instance_1 = new lib.Tween2("synched",0);
	this.instance_1.setTransform(251.2,225.8,1.007,1.007);

	this.instance_2 = new lib.Tween3("synched",0);
	this.instance_2.setTransform(251.2,225.8,1.007,1.007);
	this.instance_2._off = true;

	this.instance_3 = new lib.Tween4("synched",0);
	this.instance_3.setTransform(311.7,271.4,1.007,1.007);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance}]},68).to({state:[{t:this.instance_1,p:{x:251.2}}]},14).to({state:[{t:this.instance_1,p:{x:249.2}}]},7).to({state:[{t:this.instance_2}]},3).to({state:[{t:this.instance_2}]},7).to({state:[{t:this.instance_3}]},9).to({state:[]},1).to({state:[{t:this.instance}]},58).to({state:[{t:this.instance_1,p:{x:251.2}}]},14).to({state:[{t:this.instance_1,p:{x:249.2}}]},7).to({state:[{t:this.instance_2}]},3).to({state:[{t:this.instance_2}]},7).to({state:[{t:this.instance_3}]},9).to({state:[]},1).wait(53));
	this.timeline.addTween(cjs.Tween.get(this.instance).wait(68).to({_off:false},0).to({_off:true,x:251.2,y:225.8},14).wait(85).to({_off:false,x:120.3,y:276.3},0).to({_off:true,x:251.2,y:225.8},14).wait(80));
	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(92).to({_off:false},0).wait(7).to({startPosition:0},0).to({_off:true,x:311.7,y:271.4},9).wait(83).to({_off:false,x:251.2,y:225.8},0).wait(7).to({startPosition:0},0).to({_off:true,x:311.7,y:271.4},9).wait(54));

	// C2A
	this.instance_4 = new lib.c2a();
	this.instance_4.setTransform(242.7,191.3,1,1,0,0,0,55.5,17.5);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(48).to({_off:false},0).to({y:168.5,alpha:1},9,cjs.Ease.get(1)).to({x:242.5,y:174.5},7,cjs.Ease.get(0.5)).wait(25).to({regX:35.1,regY:64.5,scaleX:0.91,scaleY:0.91,x:222.6,y:221},0).wait(3).to({regX:55.5,regY:17.5,scaleX:1,scaleY:1,x:242.5,y:174.5},0).wait(96).to({regX:35.1,regY:64.5,scaleX:0.91,scaleY:0.91,x:222.6,y:221},0).wait(3).to({regX:55.5,regY:17.5,scaleX:1,scaleY:1,x:242.5,y:174.5},0).wait(52).to({x:242.7,y:174.7},0).to({y:171.7},5).to({y:189.7,alpha:0},9).to({_off:true},1).wait(3));

	// mr UW
	this.instance_5 = new lib.mrUWcopy();
	this.instance_5.setTransform(-120.6,138.2,0.945,0.945);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(48).to({_off:false},0).to({x:40.1},10,cjs.Ease.get(1)).to({x:30.6},4,cjs.Ease.get(1)).wait(185).to({x:40.1},3).to({x:-120.6},6,cjs.Ease.get(1)).to({_off:true},1).wait(4));

	// HL 1
	this.instance_6 = new lib.HL2();
	this.instance_6.setTransform(82.9,43.7,3.202,3.202,0,0,0,70.4,33);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(116).to({_off:false},0).to({regX:70.3,scaleX:0.7,scaleY:0.7,x:82.7,y:43.8,alpha:1},10,cjs.Ease.get(1)).to({regX:70.4,scaleX:1,scaleY:1,x:82.5,y:44},6,cjs.Ease.get(0.5)).wait(115).to({x:82.8,y:43.9},0).to({scaleX:0.93,scaleY:0.93,y:43.8},3).to({scaleX:2.55,scaleY:2.55,y:43.7,alpha:0},5).to({_off:true},1).wait(5));

	// HL 1
	this.instance_7 = new lib.HL();
	this.instance_7.setTransform(83.2,43.7,3.202,3.202,0,0,0,70.4,33);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(6).to({_off:false},0).to({regX:70.3,scaleX:0.7,scaleY:0.7,x:83.1,y:43.8,alpha:1},10,cjs.Ease.get(1)).to({regX:70.4,scaleX:1,scaleY:1,x:82.9,y:44},6,cjs.Ease.get(0.5)).wait(86).to({x:83.1,y:43.9},0).to({scaleX:0.93,scaleY:0.93,y:43.8},3).to({scaleX:2.55,scaleY:2.55,x:83.2,y:43.7,alpha:0},5).to({_off:true},1).wait(144));

	// Logo
	this.instance_8 = new lib.logo();
	this.instance_8.setTransform(148.2,214.5,1,1,0,0,0,60.8,29.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(261));

	// bg
	this.instance_9 = new lib.bg_300_2();

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(261));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(149.5,124.5,301,251.1);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;