(function (lib) { (function(){lib.bind=function(f,t){return Function.prototype.bind?f.bind(t):function(){f.apply(t,arguments);};};lib.array=function(a){for(var i=0,r=[],l=a.length;i<l;r[i]=a[i],i+=1);return r;};lib.trim=function(s){return String.prototype.trim?String.prototype.trim.call(String(s)):String(s).replace(/^\s+|\s+$/g,'');};lib.formatString=function(){var i,s=arguments[0];for(i=1;i<arguments.length;i+=1){s=s.replace(new RegExp('\\{'+(i-1)+'\\}','gm'),arguments[i]);}
return s;};lib.evalScript=function(s,t){var r,f;if(s){try{lib.currentTarget=t;f=new Function('lib',s);r=f.apply(t,[lib]);lib.currentTarget=void 0;}catch(error){lib.log('EVAL_SCRIPT',error);}}
return r;};}());(function(){var TRACE=true,log='';lib.debug=!!(lib.debug||String(window.location.hash).indexOf(lib.name+'.debug')>-1);lib.log=function(){var date,stack,args=lib.array(arguments);try{if(TRACE){stack=new Error().stack.match(/((https?:)?\/\/.+?):(\d+:\d+)/g);stack.splice(0,1);args.unshift('\n\n\n');args.push('\n\n\n');args.push(stack.join('\n'));}}catch(error){}
date=new Date();if(date.toLocaleTimeString&&date.getMilliseconds){args.unshift(date.toLocaleTimeString()+'.'+date.getMilliseconds());}
log+=args.join(' \n');if(lib.debug&&window.console){try{console.log.apply(console,args);}catch(error){console.log(args.toString());}}};lib.getLog=function(){return log;};}());(function(){lib.error=function(type,message,error,rand){lib.log('ERROR',type,message,error);rand=rand>=0?rand:0.95;error=error||{};var e={};e.version=lib.version;e.message=type+':'+message;e.description=error.name&&error.name+':'+error.message;e.file=error.fileName&&error.fileName+':'+error.lineNumber;e.stack=error.stack&&error.stack.toString().substr(0,1000);if(Math.random()>=rand){(new Image()).src=lib.path+'errorreport.php?publickey='+lib.publickey+'&msgkey=remotedata&error='+encodeURIComponent(lib.JSON.stringify(e));}};}());(function(){lib.getCSS=function(e,p,d){d=d||'';return e.style[p]?e.style[p]:window.getComputedStyle?window.getComputedStyle(e)[p]:e.currentStyle?e.currentStyle[p]:d;};}());(function(){var style,addedCSS={},head=document.getElementsByTagName('head')[0]||document.documentElement;lib.addCSS=function(css,key){if(!style){style=document.createElement('style');style.type='text/css';head.insertBefore(style,head.firstChild);}
if(!css||key in addedCSS){return;}
if(style.textContent!==void 0){style.textContent+=css;}else{style.styleSheet.cssText+=css;}
if(key){addedCSS[key]=true;}};}());(function(){lib.getRect=function(element){var r=element.getBoundingClientRect();if(r.width===void 0){return{top:r.top,bottom:r.bottom,left:r.left,right:r.right,width:r.right-r.left,height:r.bottom-r.top};}
return r;};}());(function(){var NAME='EVENT',ERROR_DISPATCH='error dispatching ',ERROR_FUNCTION=' listener is no function';lib.event={CLICK:'click',COMPLETE:'complete',INIT:'init',INSIGHT:'insight',LOAD:'load',MESSAGE:'message',MOUSEDOWN:'mousedown',MOUSEOVER:'mouseover',MOUSEOUT:'mouseout',ORIENTATION_CHANGE:'orientationchange',RESIZE:'resize',SCROLL:'scroll',UNLOAD:'unload',ADD_ITEM:'additem',COUNT_ENGAGEMENT:'countengagement',IS_ARTICLE:'isarticle',RECOMMENDATION_SEEN:'recommendationseen',SEND_ITEM:'senditem',SEND_CATEGORY:'sendcategory',WIDGET_LOAD:'widgetload',WIDGET_VIEW:'widgetview',WIDGET_INIT:'widgetinit',WIDGET_REQUEST:'widgetrequest'};function EventDispatcher(){var listeners={};function callListener(listener,type,data){try{listener.call(this,data);}catch(error){if(lib.debug){throw error;}
lib.error(NAME,ERROR_DISPATCH+type,error);}}
this.addEventListener=function(type,listener,element){if(typeof listener!=='function'){throw new Error(type+ERROR_FUNCTION);}
if(element===void 0){listeners[type]=listeners[type]||[];listeners[type].push(listener);}else if(element.addEventListener){element.addEventListener(type,listener,false);}else if(element.attachEvent){element.attachEvent('on'+type,listener);}};this.removeEventListener=function(type,listener,element){var i,ls;if(element===void 0){if(listener===void 0){listeners[type]=[];}else if(listeners[type]){ls=listeners[type];for(i=0;i<ls.length;i+=1){if(ls[i]===listener){ls[i]=void 0;}}}}else if(element.removeEventListener){element.removeEventListener(type,listener,false);}else if(element.detachEvent){element.detachEvent('on'+type,listener);}};this.dispatchEvent=function(type,data){var ls,i;lib.log(NAME,type,data);if(typeof this['on'+type]==='function'){callListener.call(this,this['on'+type],type,data);}
if(listeners[type]){ls=listeners[type];for(i=0;i<ls.length;i+=1){if(ls[i]){callListener.call(this,ls[i],type,data);}}
for(i=ls.length-1;i>=0;i-=1){if(ls[i]===void 0){ls.splice(i,1);}}}};}
lib.EventDispatcher=EventDispatcher;lib.EventDispatcher.call(lib);}());(function(){var t,json={name:lib.name,publickey:lib.publickey,sb:lib.debug||lib.sandbox||void 0};lib.call=function(name,data,bvd){var req=[name];if(data){req.push(data);}
json.req=json.req||[];json.req.push(req);json.objectid=lib.getObjectId();json.nt=lib.noTracking;json.ssp=lib.ssp;json.geo=lib.geo;json.app=lib.isApp;if(bvd){json.bvd=lib.bvd;}
clearTimeout(t);t=setTimeout(function(){lib.callRequest(json);json.req=void 0;json.bvd=void 0;if(bvd){lib.bvd={};}},50);};lib.callRequest=function(data){lib.loadScript(lib.path+'async_lib.js?json='+encodeURIComponent(lib.JSON.stringify(data))+'&x='+(new Date()).getTime());};lib.bvd={};}());(function(){var y,v=[],MIN=10,TICK=250,AMP=false,lastChanges;function Visibility(widget){this.widget=widget;this.reset();this.isVisible();}
Visibility.prototype.calculate=function(){var x,b,w,r;if(!AMP){r=lib.getRect(this.widget.container);w=getWindowRect();}else if(!this.lastChange){return false;}else{r=this.lastChange.boundingClientRect;w=this.lastChange.rootBounds;}
if(r.width<=MIN||r.height<=MIN){return false;}
if(this.widget.view.last){b=r.bottom<=w.height&&r.bottom>=0;}else{x=r.height*this.widget.view.percent;b=r.bottom>=x&&r.top<=w.height-x;}
if(!AMP){return b&&r.right>=0&&r.left<=(w.width-100)&&w.scrollHeight>=(r.height+50);}
return b;};Visibility.prototype.isVisible=function(){if(this.calculate()){var t=(new Date()).getTime()-this.t;if(t>=this.widget.view.time){this.send();return true;}}else{this.reset();}
return false;};Visibility.prototype.send=function(){lib.call(lib.event.WIDGET_VIEW,{eventtype:14,widgetname:this.widget.name,bv:this.widget.bv,items:this.widget.items,campaigns:this.widget.campaigns});this.widget.dispatchEvent(lib.event.WIDGET_VIEW);};Visibility.prototype.reset=function(){this.t=(new Date()).getTime();};function init(widget){if(lib.hasAdBlock()===1||lib.sandbox||window.$sf){return;}
v.push(new Visibility(widget));y=y||setInterval(tick,TICK);if(lastChanges){observeIntersection(lastChanges);lastChanges=null;}}
function tick(){for(var i=0;i<v.length;i+=1){if(v[i]&&v[i].isVisible()){v[i]=void 0;}}}
function unload(){clearInterval(y);y=void 0;v=[];}
function observeIntersection(changes){if(!v.length){lastChanges=changes;return;}
for(var z=0;z<changes.length;z+=1){for(var i=0;i<v.length;i+=1){if(v[i]){v[i].lastChange=changes[z];if(v[i].isVisible()){v[i]=void 0;}}}}}
function getWindowRect(){var db=document.body,de=document.documentElement;return{width:window.innerWidth||de.clientWidth||db.clientWidth,height:window.innerHeight||de.clientHeight||db.clientHeight,scrollHeight:Math.max(db.scrollHeight,db.offsetHeight,de.clientHeight,de.scrollHeight,de.offsetHeight)}}
if(window.context&&window.context.observeIntersection){AMP=true;window.context.observeIntersection(observeIntersection);}
lib.addEventListener(lib.event.WIDGET_INIT,init);lib.addEventListener(lib.event.UNLOAD,unload);}());(function(lib,document,window){var height=14,width=16,mwidth=112,pxr=window.devicePixelRatio>1?2:1,cs=lib.prefix+'oba';function init(){lib.addCSS(''+'.'+cs+'{display:block;cursor:pointer;margin-left:4px;width:'+width+'px;height:'+height+'px;background-repeat:no-repeat}'+'.'+cs+':hover{width:'+mwidth+'px}'+'.'+cs+'_hint{width:'+mwidth+'px!important}'+'.'+cs+'_right{float:right;background-position:right top}'+'.'+cs+'_right:hover{background-position:right -'+height+'px;}'+'.'+cs+'_left{margin-left:0}'+'.'+cs+'_left:hover{background-position:left -'+height+'px;}'+'span[data-oba="text"]:hover{color:transparent!important;white-space:nowrap;}'+'span[data-oba="text"] .'+cs+'{margin-top:-1px;}'+'span[data-oba="text"] .'+cs+'_left{float:left;}','oba');}
function background(p,a,t,l){return'url('+lib.cdnpath+'image/'+(p.getAttribute('data-pcd')?'pcd':'ad')+'choices'+(t?'2':'')+'/'+l+'/'+((height-1)*pxr)+'/'+color(p)+'/'+a+'/1.png'+')';}
function color(p){var c=lib.getCSS(p,'color');if(c){c=c.replace(/ /g,'').match(/([0-9]+),([0-9]+),([0-9]+)/);c=c&&c[0]?c[0]:null;}
return c||'939393';}
function position(p){var l,n=document.createElement('span');n.className='plista-oba-image';p.parentNode.insertBefore(n,p);l=lib.getCSS(n,'position','static')==='absolute';p.parentNode.removeChild(n);return l?'left':'right';}
function paint(p,widget){if(p.hasOBA){return;}
p.hasOBA=true;var t,l=widget.language,o=widget.optout,s=document.createElement('span');s.setAttribute('data-optout',o);s.className=cs;s.onclick=click;if(pxr===2){s.style.backgroundSize='auto '+(height*pxr)+'px';}
if(widget.oba===1){s.style.backgroundImage=background(p,0,0,l);s.className+=' '+cs+'_right';p.style.textAlign='right';p.insertBefore(s,p.firstChild);}else{t=p.getAttribute('data-oba').match(/^2;/);if(p.tagName.toLowerCase()==='img'){s.className+=' '+cs+'_hint';}
if(p.getAttribute('data-position')==='left'||position(p)==='left'){s.style.backgroundImage=background(p,2,t,l);s.className+=' '+cs+'_left';}else{s.style.backgroundImage=background(p,0,t,l);s.className+=' '+cs+'_right';}
if(p.tagName==='SPAN'&&p.className.indexOf('plistaPetImg')>-1){p.setAttribute('data-oba','text');p.appendChild(s);}else{p.parentNode.insertBefore(s,p);p.parentNode.removeChild(p);s.className='plista-oba '+s.className;}}}
function click(e){window.open(this.getAttribute('data-optout'),'_newtab');e=e||window.event;e.cancelBubble=true;if(e.stopPropagation){e.stopPropagation();}
return false;}
function render(widget){var i,q,w;if(widget.container&&widget.container.id){if(widget.oba===1){q='#'+widget.container.id+' .plista-powered, #'+widget.container.id+' [title="powered by plista"]';}else if(widget.oba===2){q='#'+widget.container.id+' span[data-oba], #'+widget.container.id+' img[data-oba]';}
w=lib.querySelectorAll(q);for(i=0;i<w.length;i+=1){paint(w[i],widget);}
if(widget.oba!==1){return;}
q='#'+widget.container.id+' img[alt="plista Blume"], #'+widget.container.id+' img[alt="powered by plista"]';w=lib.querySelectorAll(q);for(i=0;i<w.length;i+=1){paint(w[i].parentNode,widget);}
q='#'+widget.container.id+' img[src*="logo_plista_"]';try{w=lib.querySelectorAll(q);}catch(error){w=[];}
for(i=0;i<w.length;i+=1){paint(w[i].parentNode,widget);}}}
lib.addEventListener(lib.event.WIDGET_INIT,render);lib.addEventListener(lib.event.LOAD,init);}(lib,document,window));(function(){lib.context={};var widget=lib.placements[0],ATTR_REPLACE='data-replace-url',ATTR_REDIRECT='data-redirect',ATTR_MOUSEDOWN='this.href=this.getAttribute(\''+ATTR_REDIRECT+'\');';function replaceUrl(){var i,a,t=lib.querySelectorAll('#'+this.uid+' ['+ATTR_REPLACE+']');for(i=0;i<t.length;i+=1){a=t[i];a.setAttribute(ATTR_REDIRECT,a.href);a.href=a.getAttribute(ATTR_REPLACE);a.setAttribute('onmousedown',ATTR_MOUSEDOWN);a.removeAttribute(ATTR_REPLACE);}}
lib.isTouch='ontouchstart'in document.documentElement;lib.hasFlash=lib.hasVideo=function(){return true;};lib.hasAdBlock=function(){return false;};try{lib.isFrame=!!(window.frameElement)||void 0;}catch(error){lib.isFrame=true;}
widget.container=document.getElementById(widget.uid);widget.dispatchEvent=function(){};if(widget.replaceURL&&!lib.isTouch){replaceUrl.call(widget);}
if(lib.isFrame&&lib.token){setTimeout(function(){(new Image()).src=lib.path+'sws.php?t='+lib.token+'&w='+widget.container.offsetWidth+'&h='+widget.container.offsetHeight;},3000);}
lib.addCSS('#'+widget.uid+' [data-type="flashPet"] {display:block !important;}');lib.dispatchEvent(lib.event.LOAD);lib.dispatchEvent(lib.event.WIDGET_INIT,widget);lib.dispatchEvent(lib.event.COMPLETE);}());
}(PLISTA_TINY[0]));